export const DAYS_PER_YEAR = 365
export const MILLISECONDS_PER_SECOND = 1000
export const MILLISECONDS_PER_FIVE_SECONDS = MILLISECONDS_PER_SECOND * 5
export const MILLISECONDS_PER_MINUTE = MILLISECONDS_PER_SECOND * 60
export const MILLISECONDS_PER_TWO_MINUTES = MILLISECONDS_PER_MINUTE * 2
export const MILLISECONDS_PER_HOUR = MILLISECONDS_PER_MINUTE * 60
export const MILLISECONDS_PER_DAY = MILLISECONDS_PER_HOUR * 24
export const MILLISECONDS_PER_WEEK = MILLISECONDS_PER_DAY * 7
export const MILLISECONDS_PER_MONTH = MILLISECONDS_PER_DAY * 30
export const MILLISECONDS_PER_YEAR = MILLISECONDS_PER_DAY * DAYS_PER_YEAR
export const SECONDS_PER_MINUTE = Math.floor(
  MILLISECONDS_PER_MINUTE / MILLISECONDS_PER_SECOND
)
export const SECONDS_PER_HOUR = Math.floor(
  MILLISECONDS_PER_HOUR / MILLISECONDS_PER_SECOND
)
export const SECONDS_PER_DAY = Math.floor(
  MILLISECONDS_PER_DAY / MILLISECONDS_PER_SECOND
)
export const SECONDS_PER_MONTH = Math.floor(
  MILLISECONDS_PER_MONTH / MILLISECONDS_PER_SECOND
)
export const SECONDS_PER_WEEK = Math.floor(
  MILLISECONDS_PER_WEEK / MILLISECONDS_PER_SECOND
)
export const SECONDS_PER_YEAR = Math.floor(
  MILLISECONDS_PER_YEAR / MILLISECONDS_PER_SECOND
)
