/**
 * This is the whitelist of deeplinks that are allowed to be opened in the app
 * It is used to prevent malicious deeplinks from being opened in the app
 * It is also used to prevent deeplinks from being opened in the app that are not allowed
 **/
export const DEEPLINK_WHITELIST = [
  'core://solanalaunch',
  'core://stakecomplete',
  'core://watchlist',
  'core://portfolio',
  'core://onrampcompleted',
  'core://offrampcompleted',
  'core://receive',
  'core://tracktokendetail',
  'core://track',
  'core://meld/onramp',
  'core://meld/offramp',
  'core://stake',
  'core://claimstakereward',
  'core://addstake',
  'core://discovercollectibles',
  'core://collectiblemanagement',
  'core://tokenmanagement',
  'core://send',
  'core://swap',
  'core://walletconnectscan',
  'core://activity',
  'core://browser',
  'core://browser/tabs',
  'core://browser/history',
  'core://accountsettings',
  'core://accountsettings/selectcurrency',
  'core://accountsettings/selectappearance',
  'core://accountsettings/securityandprivacy',
  'core://accountsettings/connectedsites',
  'core://accountsettings/changepin',
  'core://accountsettings/manageaccounts',
  'core://accountsettings/managenetworks',
  'core://accountsettings/addressbook',
  'core://accountsettings/selectavatar',
  'core://accountsettings/notificationpreferences',
  'core://accountsettings/importwallet',
  'core://accountsettings/importprivatekey',
  'core://accountsettings/importseedwallet'
]
