export enum ServiceProviderCategories {
  BANK_LINKING = 'BANK_LINKING',
  CRYPTO_ONRAMP = 'CRYPTO_ONRAMP',
  CRYPTO_OFFRAMP = 'CRYPTO_OFFRAMP',
  CRYPTO_TRANSFER = 'CRYPTO_TRANSFER',
  FIAT_PAYMENTS = 'FIAT_PAYMENTS'
}

export enum ServiceProviderStatus {
  LIVE = 'LIVE',
  RECENTLY_ADDED = 'RECENTLY_ADDED',
  BUILDING = 'BUILDING'
}

export enum MELD_CURRENCY_CODES {
  BTC = 'BTC',
  USDC = 'USDC',
  AVAXC = 'AVAXC'
}

export const NATIVE_ERC20_TOKEN_CONTRACT_ADDRESS =
  '0x0000000000000000000000000000000000000000'
