export enum ServiceProviderCategories {
  BANK_LINKING = 'BANK_LINKING',
  CRYPTO_ONRAMP = 'CRYPTO_ONRAMP',
  CRYPTO_OFFRAMP = 'CRYPTO_OFFRAMP',
  CRYPTO_TRANSFER = 'CRYPTO_TRANSFER',
  FIAT_PAYMENTS = 'FIAT_PAYMENTS'
}

export enum ServiceProviderStatus {
  LIVE = 'LIVE',
  RECENTLY_ADDED = 'RECENTLY_ADDED',
  BUILDING = 'BUILDING'
}

export enum MELD_CURRENCY_CODES {
  BTC = 'BTC',
  USDC = 'USDC',
  AVAXC = 'AVAXC'
}

export const NATIVE_ERC20_TOKEN_CONTRACT_ADDRESS =
  '0x0000000000000000000000000000000000000000'

export enum PaymentMethods {
  CREDIT_DEBIT_CARD = 'Debit/credit card',
  APPLE_PAY = 'Apple Pay',
  GOOGLE_PAY = 'Google Pay',
  SEPA = 'SEPA',
  PIX = 'PIX',
  BINANCE_CASH_BALANCE = 'Binance Cash Balance',
  COINBASE_CASH_BALANCE = 'Coinbase Cash Balance',
  ACH = 'ACH',
  KHIPU = 'KhIPU',
  PSE = 'PSE',
  REVOLUT_PAY = 'Revolut Pay',
  QRIS = 'QRIS',
  OVO = 'OVO',
  UPI = 'UPI',
  IMPS = 'IMPS',
  MOBILE_MONEY = 'Mobile Money',
  BINANCE_P2P = 'Binance P2P',
  SPEI = 'SPEI',
  PAYMAYA = 'PayMaya',
  GCASH = 'GCash',
  GRABPAY = 'GrabPay',
  THAI_QR = 'Thai QR',
  FAST = 'FAST',
  ROBINHOOD_BUYING_POWER = 'Robinhood Buying Power',
  VIETQR = 'Viet QR',
  VIETTELPAY = 'Viettel Pay',
  OPEN_BANKING = 'Instant Bank Transfer - Open Banking',
  INSTAPAY = 'Instapay',
  ASTROPAY = 'Astropay',
  APPLEPAY_EU = 'Apple Pay EU',
  IDEAL = 'iDEAL',
  DUITNOW = 'DuitNow',
  DANA = 'DANA',
  SKRILL = 'Skrill',
  SHOPEEPAY = 'ShopeePay',
  PICPAY = 'PicPay',
  PAYID = 'PayID',
  BOOST = 'Boost',
  BANCONTACT = 'Bancontact',
  BRIVA = 'BRIVA',
  EPS = 'EPS',
  COINS_PH = 'Coins.ph',
  FPX = 'FPX',
  NETELLER = 'Neteller',
  MULTIBANCO = 'Multibanco',
  MOMO = 'Momo',
  MPESA = 'M-Pesa',
  MANDIRIVA = 'MANDIRIVA',
  SAME_DAY_ACH = 'Same Day ACH',
  STP = 'STP',
  SOFORT = 'Sofort',
  SWIFT = 'SWIFT',
  TOUCH_N_GO = `Touch'n Go`,
  UK_FASTER_PAYMENTS = 'UK Faster Payments',
  QRPH = 'QRPH',
  INTERAC = 'Interac',

  UAE_BANK_TRANSFER = 'Local Manual Bank Transfer',
  VN_BANK_TRANSFER = 'Local Manual Bank Transfer',
  NG_BANK_TRANSFER = 'Local Manual Bank Transfer',
  TH_BANK_TRANSFER = 'Local Manual Bank Transfer',
  PH_BANK_TRANSFER = 'Local Manual Bank Transfer',
  PE_BANK_TRANSFER = 'Local Manual Bank Transfer',
  MY_BANK_TRANSFER = 'Local Manual Bank Transfer',
  MX_BANK_TRANSFER = 'Local Manual Bank Transfer',
  LOCAL_BANK_TRANSFER = 'Local Manual Bank Transfer',
  ID_BANK_TRANSFER = 'Local Manual Bank Transfer',
  IN_BANK_TRANSFER = 'Local Manual Bank Transfer',
  CO_BANK_TRANSFER = 'Local Manual Bank Transfer',
  CL_BANK_TRANSFER = 'Local Manual Bank Transfer',
  AR_BANK_TRANSFER = 'Local Manual Bank Transfer',
  BR_BANK_TRANSFER = 'Local Manual Bank Transfer',
  CH_BANK_TRANSFER = 'Local Manual Bank Transfer',
  DE_BANK_TRANSFER = 'Local Manual Bank Transfer',
  ES_BANK_TRANSFER = 'Local Manual Bank Transfer',
  FR_BANK_TRANSFER = 'Local Manual Bank Transfer',
  IT_BANK_TRANSFER = 'Local Manual Bank Transfer',
  NL_BANK_TRANSFER = 'Local Manual Bank Transfer',

  PE_CASH = 'Local Cash Vouchers',
  MX_CASH = 'Local Cash Vouchers',
  EC_CASH = 'Local Cash Vouchers',
  CR_CASH = 'Local Cash Vouchers',
  CO_CASH = 'Local Cash Vouchers',
  DO_CASH = 'Local Cash Vouchers',
  GT_CASH = 'Local Cash Vouchers',
  HN_CASH = 'Local Cash Vouchers',
  NI_CASH = 'Local Cash Vouchers',
  PA_CASH = 'Local Cash Vouchers',
  PY_CASH = 'Local Cash Vouchers'
}

export enum PaymentTypes {
  Card,
  BANK_TRANSFER,
  MOBILE_WALLET,
  LOCAL,
  EXCHANGE,
  CASH
}

export enum ServiceProviders {
  AKOYA = 'Akoya',
  ALCHEMYPAY = 'Alchemy Pay',
  BTCDIRECT = 'BTC Direct',
  BANXA = 'Banxa',
  BILIRA = 'Bilira',
  BINANCECONNECT = 'Binance Connect',
  BLOCKCHAINDOTCOM = 'Blockchain.com',
  CHECKOUT = 'Checkout.com',
  CIRCLE = 'Circle',
  COINBASEPAY = 'Coinbase Pay',
  COINFLOW = 'Coinflow',
  FINICITY = 'Finicity',
  FONBNK = 'Fonbnk',
  GUARDARIAN = 'Guardarian',
  HARBOUR = 'Harbour',
  KOYWE = 'Koywe',
  MX = 'MX',
  MERCURYO = 'Mercuryo',
  MESH = 'Mesh',
  MESO = 'Meso',
  MOOV = 'Moov',
  ONMETA = 'Onmeta',
  ONRAMPMONEY = 'Onramp Money',
  PAYPAL = 'PayPal',
  PAYBIS = 'Paybis',
  PLAID = 'Plaid',
  REVOLUT = 'Revolut',
  ROBINHOOD = 'Robinhood',
  SALTEDGE = 'Saltedge',
  SALTEDGEPARTNERS = 'Salt Edge (Partners)',
  SARDINE = 'Sardine',
  SHIFT4 = 'Shift4',
  SIMPLEX = 'Simplex',
  STRIPE = 'Stripe',
  TOPPER = 'Topper',
  TRANSFI = 'Transfi',
  TRANSAK = 'Transak',
  UNLIMIT = 'Unlimit',
  YELLOWCARD = 'Yellow Card',
  YODLEE = 'Yodlee'
}
