export enum ServiceProviderCategories {
  BANK_LINKING = 'BANK_LINKING',
  CRYPTO_ONRAMP = 'CRYPTO_ONRAMP',
  CRYPTO_OFFRAMP = 'CRYPTO_OFFRAMP',
  CRYPTO_TRANSFER = 'CRYPTO_TRANSFER',
  FIAT_PAYMENTS = 'FIAT_PAYMENTS'
}

export enum ServiceProviderStatus {
  LIVE = 'LIVE',
  RECENTLY_ADDED = 'RECENTLY_ADDED',
  BUILDING = 'BUILDING'
}

export enum MELD_CURRENCY_CODES {
  BTC = 'BTC',
  USDC = 'USDC',
  AVAXC = 'AVAXC'
}

export const NATIVE_ERC20_TOKEN_CONTRACT_ADDRESS =
  '0x0000000000000000000000000000000000000000'

export enum PaymentMethods {
  CREDIT_DEBIT_CARD = 'CREDIT_DEBIT_CARD',
  APPLE_PAY = 'APPLE_PAY',
  GOOGLE_PAY = 'GOOGLE_PAY',
  SEPA = 'SEPA',
  PIX = 'PIX',
  BINANCE_CASH_BALANCE = 'BINANCE_CASH_BALANCE',
  COINBASE_CASH_BALANCE = 'COINBASE_CASH_BALANCE',
  ACH = 'ACH',
  KHIPU = 'KHIPU',
  PSE = 'PSE',
  REVOLUT_PAY = 'REVOLUT_PAY',
  QRIS = 'QRIS',
  OVO = 'OVO',
  UPI = 'UPI',
  IMPS = 'IMPS',
  MOBILE_MONEY = 'MOBILE_MONEY',
  BINANCE_P2P = 'BINANCE_P2P',
  SPEI = 'SPEI',
  PAYMAYA = 'PAYMAYA',
  GCASH = 'GCASH',
  GRABPAY = 'GRABPAY',
  THAI_QR = 'THAI_QR',
  FAST = 'FAST',
  ROBINHOOD_BUYING_POWER = 'ROBINHOOD_BUYING_POWER',
  VIETQR = 'VIETQR',
  VIETTELPAY = 'VIETTELPAY',
  OPEN_BANKING = 'OPEN_BANKING',
  INSTAPAY = 'INSTAPAY',
  ASTROPAY = 'ASTROPAY',
  APPLEPAY_EU = 'APPLEPAY_EU',
  IDEAL = 'IDEAL',
  DUITNOW = 'DUITNOW',
  DANA = 'DANA',
  SKRILL = 'SKRILL',
  SHOPEEPAY = 'SHOPEEPAY',
  PICPAY = 'PICPAY',
  PAYID = 'PAYID',
  PAYPAL = 'PAYPAL',
  BANCONTACT = 'BANCONTACT',
  BRIVA = 'BRIVA',
  EPS = 'EPS',
  COINS_PH = 'COINS_PH',
  FPX = 'FPX',
  NETELLER = 'NETELLER',
  PAY_NOW = 'PAY_NOW',
  NEFT = 'NEFT',
  MULTIBANCO = 'MULTIBANCO',
  MOMO = 'MOMO',
  MPESA = 'MPESA',
  MANDIRIVA = 'MANDIRIVA',
  SAME_DAY_ACH = 'SAME_DAY_ACH',
  STP = 'STP',
  SOFORT = 'SOFORT',
  SWIFT = 'SWIFT',
  TOUCH_N_GO = 'TOUCH_N_GO',
  UK_FASTER_PAYMENTS = 'UK_FASTER_PAYMENTS',
  QRPH = 'QRPH',
  INTERAC = 'INTERAC',
  ZALOPAY = 'ZALOPAY',
  PROMPTPAY = 'PROMPTPAY',
  BLIK = 'BLIK',
  UAE_BANK_TRANSFER = 'UAE_BANK_TRANSFER',
  VN_BANK_TRANSFER = 'VN_BANK_TRANSFER',
  NG_BANK_TRANSFER = 'NG_BANK_TRANSFER',
  TH_BANK_TRANSFER = 'TH_BANK_TRANSFER',
  PH_BANK_TRANSFER = 'PH_BANK_TRANSFER',
  PE_BANK_TRANSFER = 'PE_BANK_TRANSFER',
  MY_BANK_TRANSFER = 'MY_BANK_TRANSFER',
  MX_BANK_TRANSFER = 'MX_BANK_TRANSFER',
  LOCAL_BANK_TRANSFER = 'LOCAL_BANK_TRANSFER',
  ID_BANK_TRANSFER = 'ID_BANK_TRANSFER',
  IN_BANK_TRANSFER = 'IN_BANK_TRANSFER',
  CO_BANK_TRANSFER = 'CO_BANK_TRANSFER',
  CL_BANK_TRANSFER = 'CL_BANK_TRANSFER',
  AR_BANK_TRANSFER = 'AR_BANK_TRANSFER',
  BR_BANK_TRANSFER = 'BR_BANK_TRANSFER',
  CH_BANK_TRANSFER = 'CH_BANK_TRANSFER',
  DE_BANK_TRANSFER = 'DE_BANK_TRANSFER',
  ES_BANK_TRANSFER = 'ES_BANK_TRANSFER',
  FR_BANK_TRANSFER = 'FR_BANK_TRANSFER',
  IT_BANK_TRANSFER = 'IT_BANK_TRANSFER',
  NL_BANK_TRANSFER = 'NL_BANK_TRANSFER',
  TODITO_CASH = 'TODITO_CASH',
  PE_CASH = 'PE_CASH',
  MX_CASH = 'MX_CASH',
  EC_CASH = 'EC_CASH',
  CR_CASH = 'CR_CASH',
  CO_CASH = 'CO_CASH',
  DO_CASH = 'DO_CASH',
  GT_CASH = 'GT_CASH',
  HN_CASH = 'HN_CASH',
  NI_CASH = 'NI_CASH',
  PA_CASH = 'PA_CASH',
  PH_CASH = 'PH_CASH',
  PY_CASH = 'PY_CASH'
}

export const PaymentMethodNames = {
  [PaymentMethods.CREDIT_DEBIT_CARD]: 'Debit/credit card',
  [PaymentMethods.APPLE_PAY]: 'Apple Pay',
  [PaymentMethods.GOOGLE_PAY]: 'Google Pay',
  [PaymentMethods.SEPA]: 'SEPA',
  [PaymentMethods.PIX]: 'PIX',
  [PaymentMethods.BINANCE_CASH_BALANCE]: 'Binance Cash Balance',
  [PaymentMethods.COINBASE_CASH_BALANCE]: 'Coinbase Cash Balance',
  [PaymentMethods.ACH]: 'ACH',
  [PaymentMethods.KHIPU]: 'KhIPU',
  [PaymentMethods.PSE]: 'PSE',
  [PaymentMethods.REVOLUT_PAY]: 'Revolut Pay',
  [PaymentMethods.QRIS]: 'QRIS',
  [PaymentMethods.OVO]: 'OVO',
  [PaymentMethods.UPI]: 'UPI',
  [PaymentMethods.IMPS]: 'IMPS',
  [PaymentMethods.MOBILE_MONEY]: 'Mobile Money',
  [PaymentMethods.BINANCE_P2P]: 'Binance P2P',
  [PaymentMethods.SPEI]: 'SPEI',
  [PaymentMethods.PAYMAYA]: 'PayMaya',
  [PaymentMethods.GCASH]: 'GCash',
  [PaymentMethods.GRABPAY]: 'GrabPay',
  [PaymentMethods.THAI_QR]: 'Thai QR',
  [PaymentMethods.FAST]: 'FAST',
  [PaymentMethods.ROBINHOOD_BUYING_POWER]: 'Robinhood Buying Power',
  [PaymentMethods.VIETQR]: 'Viet QR',
  [PaymentMethods.VIETTELPAY]: 'Viettel Pay',
  [PaymentMethods.OPEN_BANKING]: 'Instant Bank Transfer - Open Banking',
  [PaymentMethods.INSTAPAY]: 'Instapay',
  [PaymentMethods.ASTROPAY]: 'Astropay',
  [PaymentMethods.APPLEPAY_EU]: 'Apple Pay EU',
  [PaymentMethods.IDEAL]: 'iDEAL',
  [PaymentMethods.DUITNOW]: 'DuitNow',
  [PaymentMethods.DANA]: 'DANA',
  [PaymentMethods.SKRILL]: 'Skrill',
  [PaymentMethods.SHOPEEPAY]: 'ShopeePay',
  [PaymentMethods.PICPAY]: 'PicPay',
  [PaymentMethods.BLIK]: 'Blik',
  [PaymentMethods.PAYID]: 'PayID',
  [PaymentMethods.PROMPTPAY]: 'PromptPay',
  [PaymentMethods.PAY_NOW]: 'PayNow',
  [PaymentMethods.PAYPAL]: 'PayPal',
  [PaymentMethods.BANCONTACT]: 'Bancontact',
  [PaymentMethods.BRIVA]: 'BRIVA',
  [PaymentMethods.EPS]: 'EPS',
  [PaymentMethods.COINS_PH]: 'Coins.ph',
  [PaymentMethods.FPX]: 'FPX',
  [PaymentMethods.NETELLER]: 'Neteller',
  [PaymentMethods.MULTIBANCO]: 'Multibanco',
  [PaymentMethods.MOMO]: 'Momo',
  [PaymentMethods.MPESA]: 'M-Pesa',
  [PaymentMethods.MANDIRIVA]: 'MANDIRIVA',
  [PaymentMethods.SAME_DAY_ACH]: 'Same Day ACH',
  [PaymentMethods.STP]: 'STP',
  [PaymentMethods.SOFORT]: 'Sofort',
  [PaymentMethods.SWIFT]: 'SWIFT',
  [PaymentMethods.TOUCH_N_GO]: `Touch'n Go`,
  [PaymentMethods.UK_FASTER_PAYMENTS]: 'UK Faster Payments',
  [PaymentMethods.QRPH]: 'QRPH',
  [PaymentMethods.INTERAC]: 'Interac',
  [PaymentMethods.ZALOPAY]: 'Zalopay',
  [PaymentMethods.NEFT]: 'NEFT',
  [PaymentMethods.TODITO_CASH]: 'Todito Cash',
  [PaymentMethods.UAE_BANK_TRANSFER]: 'Local Manual Bank Transfer',
  [PaymentMethods.VN_BANK_TRANSFER]: 'Local Manual Bank Transfer',
  [PaymentMethods.NG_BANK_TRANSFER]: 'Local Manual Bank Transfer',
  [PaymentMethods.TH_BANK_TRANSFER]: 'Local Manual Bank Transfer',
  [PaymentMethods.PH_BANK_TRANSFER]: 'Local Manual Bank Transfer',
  [PaymentMethods.PE_BANK_TRANSFER]: 'Local Manual Bank Transfer',
  [PaymentMethods.MY_BANK_TRANSFER]: 'Local Manual Bank Transfer',
  [PaymentMethods.MX_BANK_TRANSFER]: 'Local Manual Bank Transfer',
  [PaymentMethods.LOCAL_BANK_TRANSFER]: 'Local Manual Bank Transfer',
  [PaymentMethods.ID_BANK_TRANSFER]: 'Local Manual Bank Transfer',
  [PaymentMethods.IN_BANK_TRANSFER]: 'Local Manual Bank Transfer',
  [PaymentMethods.CO_BANK_TRANSFER]: 'Local Manual Bank Transfer',
  [PaymentMethods.CL_BANK_TRANSFER]: 'Local Manual Bank Transfer',
  [PaymentMethods.AR_BANK_TRANSFER]: 'Local Manual Bank Transfer',
  [PaymentMethods.BR_BANK_TRANSFER]: 'Local Manual Bank Transfer',
  [PaymentMethods.CH_BANK_TRANSFER]: 'Local Manual Bank Transfer',
  [PaymentMethods.DE_BANK_TRANSFER]: 'Local Manual Bank Transfer',
  [PaymentMethods.ES_BANK_TRANSFER]: 'Local Manual Bank Transfer',
  [PaymentMethods.FR_BANK_TRANSFER]: 'Local Manual Bank Transfer',
  [PaymentMethods.IT_BANK_TRANSFER]: 'Local Manual Bank Transfer',
  [PaymentMethods.NL_BANK_TRANSFER]: 'Local Manual Bank Transfer',
  [PaymentMethods.PE_CASH]: 'Local Cash Vouchers',
  [PaymentMethods.MX_CASH]: 'Local Cash Vouchers',
  [PaymentMethods.EC_CASH]: 'Local Cash Vouchers',
  [PaymentMethods.CR_CASH]: 'Local Cash Vouchers',
  [PaymentMethods.CO_CASH]: 'Local Cash Vouchers',
  [PaymentMethods.DO_CASH]: 'Local Cash Vouchers',
  [PaymentMethods.GT_CASH]: 'Local Cash Vouchers',
  [PaymentMethods.HN_CASH]: 'Local Cash Vouchers',
  [PaymentMethods.NI_CASH]: 'Local Cash Vouchers',
  [PaymentMethods.PA_CASH]: 'Local Cash Vouchers',
  [PaymentMethods.PH_CASH]: 'Local Cash Vouchers',
  [PaymentMethods.PY_CASH]: 'Local Cash Vouchers'
}

export const PaymentMethodTimeLimits = {
  [PaymentMethods.FAST]: 'Instant',
  [PaymentMethods.REVOLUT_PAY]: 'Under 10 minutes',
  [PaymentMethods.BINANCE_P2P]: 'Under 10 minutes',
  [PaymentMethods.INSTAPAY]: 'Instant',
  [PaymentMethods.BINANCE_CASH_BALANCE]: 'Instant',
  [PaymentMethods.COINBASE_CASH_BALANCE]: 'Instant',
  [PaymentMethods.NG_BANK_TRANSFER]: 'Under 10 minutes',
  [PaymentMethods.SEPA]: '3-5 days',
  [PaymentMethods.SPEI]: 'Under 10 minutes',
  [PaymentMethods.UPI]: 'Instant',
  [PaymentMethods.ACH]: '3-5 days',
  [PaymentMethods.IMPS]: 'Instant',
  [PaymentMethods.OPEN_BANKING]: 'Instant',
  [PaymentMethods.INTERAC]: 'Instant',
  [PaymentMethods.KHIPU]: 'Under 10 minutes',
  [PaymentMethods.AR_BANK_TRANSFER]: 'Under 10 minutes',
  [PaymentMethods.BR_BANK_TRANSFER]: 'Under 10 minutes',
  [PaymentMethods.CL_BANK_TRANSFER]: 'Under 10 minutes',
  [PaymentMethods.CO_BANK_TRANSFER]: 'Under 10 minutes',
  [PaymentMethods.ID_BANK_TRANSFER]: 'Under 10 minutes',
  [PaymentMethods.LOCAL_BANK_TRANSFER]: 'Under 10 minutes',
  [PaymentMethods.MX_BANK_TRANSFER]: 'Under 10 minutes',
  [PaymentMethods.MY_BANK_TRANSFER]: 'Under 10 minutes',
  [PaymentMethods.PE_BANK_TRANSFER]: 'Under 10 minutes',
  [PaymentMethods.PH_BANK_TRANSFER]: 'Under 10 minutes',
  [PaymentMethods.NL_BANK_TRANSFER]: 'Under 10 minutes',
  [PaymentMethods.IT_BANK_TRANSFER]: 'Under 10 minutes',
  [PaymentMethods.FR_BANK_TRANSFER]: 'Under 10 minutes',
  [PaymentMethods.ES_BANK_TRANSFER]: 'Under 10 minutes',
  [PaymentMethods.DE_BANK_TRANSFER]: 'Under 10 minutes',
  [PaymentMethods.CH_BANK_TRANSFER]: 'Under 10 minutes',
  [PaymentMethods.UAE_BANK_TRANSFER]: 'Under 10 minutes',
  [PaymentMethods.VN_BANK_TRANSFER]: 'Under 10 minutes',
  [PaymentMethods.NEFT]: 'Instant',
  [PaymentMethods.PIX]: 'Instant',
  [PaymentMethods.PSE]: 'Under 10 minutes',
  [PaymentMethods.PAYID]: 'Instant',
  [PaymentMethods.PROMPTPAY]: 'Instant',
  [PaymentMethods.STP]: 'Under 10 minutes',
  [PaymentMethods.SAME_DAY_ACH]: '1 day',
  [PaymentMethods.THAI_QR]: 'Instant',
  [PaymentMethods.UK_FASTER_PAYMENTS]: 'Instant',
  [PaymentMethods.VIETQR]: 'Instant',
  [PaymentMethods.IDEAL]: 'Instant',
  [PaymentMethods.CREDIT_DEBIT_CARD]: 'Under 10 minutes',
  [PaymentMethods.CO_CASH]: 'Under 10 minutes',
  [PaymentMethods.CR_CASH]: 'Under 10 minutes',
  [PaymentMethods.EC_CASH]: 'Under 10 minutes',
  [PaymentMethods.GT_CASH]: 'Under 10 minutes',
  [PaymentMethods.MX_CASH]: 'Under 10 minutes',
  [PaymentMethods.PA_CASH]: 'Under 10 minutes',
  [PaymentMethods.PE_CASH]: 'Under 10 minutes',
  [PaymentMethods.PH_CASH]: 'Under 10 minutes',
  [PaymentMethods.PY_CASH]: 'Under 10 minutes',
  [PaymentMethods.DO_CASH]: 'Under 10 minutes',
  [PaymentMethods.HN_CASH]: 'Under 10 minutes',
  [PaymentMethods.NI_CASH]: 'Under 10 minutes',
  [PaymentMethods.ROBINHOOD_BUYING_POWER]: 'Instant',
  [PaymentMethods.COINS_PH]: 'Under 10 minutes',
  [PaymentMethods.MOBILE_MONEY]: 'Under 10 minutes',
  [PaymentMethods.PAY_NOW]: 'Under 10 minutes',
  [PaymentMethods.QRIS]: 'Instant',
  [PaymentMethods.SOFORT]: '1-3 days',
  [PaymentMethods.TODITO_CASH]: 'Instant',
  [PaymentMethods.APPLE_PAY]: 'Under 10 minutes',
  [PaymentMethods.APPLEPAY_EU]: 'Under 10 minutes',
  [PaymentMethods.ASTROPAY]: 'Under 10 minutes',
  [PaymentMethods.BANCONTACT]: 'Instant',
  [PaymentMethods.BLIK]: 'Instant',
  [PaymentMethods.DANA]: 'Instant',
  [PaymentMethods.GCASH]: 'Instant',
  [PaymentMethods.GOOGLE_PAY]: 'Under 10 minutes',
  [PaymentMethods.GRABPAY]: 'Instant',
  [PaymentMethods.MOMO]: 'Instant',
  [PaymentMethods.OVO]: 'Instant',
  [PaymentMethods.PAYMAYA]: 'Under 10 minutes',
  [PaymentMethods.PICPAY]: '1 day',
  [PaymentMethods.SHOPEEPAY]: 'Under 10 minutes',
  [PaymentMethods.VIETTELPAY]: 'Instant',
  [PaymentMethods.ZALOPAY]: 'Instant',
  [PaymentMethods.DUITNOW]: 'Instant',
  [PaymentMethods.SKRILL]: '1-3 days',
  [PaymentMethods.PAYPAL]: '1-3 days',
  [PaymentMethods.BRIVA]: 'Instant',
  [PaymentMethods.EPS]: 'Instant',
  [PaymentMethods.FPX]: 'Instant',
  [PaymentMethods.NETELLER]: '1-3 days',
  [PaymentMethods.MULTIBANCO]: '3-5 days',
  [PaymentMethods.MPESA]: 'Instant',
  [PaymentMethods.MANDIRIVA]: 'Under 10 minutes',
  [PaymentMethods.SWIFT]: '3-5 days',
  [PaymentMethods.TOUCH_N_GO]: 'Instant',
  [PaymentMethods.QRPH]: 'Instant',
  [PaymentMethods.TH_BANK_TRANSFER]: 'Under 10 minutes',
  [PaymentMethods.IN_BANK_TRANSFER]: 'Under 10 minutes'
}

export enum PaymentTypes {
  CARD,
  BANK_TRANSFER,
  MOBILE_WALLET,
  LOCAL,
  EXCHANGE,
  CASH
}

export enum ServiceProviders {
  AKOYA = 'Akoya',
  ALCHEMYPAY = 'Alchemy Pay',
  BTCDIRECT = 'BTC Direct',
  BANXA = 'Banxa',
  BILIRA = 'Bilira',
  BINANCECONNECT = 'Binance Connect',
  BLOCKCHAINDOTCOM = 'Blockchain.com',
  CHECKOUT = 'Checkout.com',
  CIRCLE = 'Circle',
  COINBASEPAY = 'Coinbase Pay',
  COINFLOW = 'Coinflow',
  FINICITY = 'Finicity',
  FONBNK = 'Fonbnk',
  GUARDARIAN = 'Guardarian',
  HARBOUR = 'Harbour',
  KOYWE = 'Koywe',
  MX = 'MX',
  MERCURYO = 'Mercuryo',
  MESH = 'Mesh',
  MESO = 'Meso',
  MOOV = 'Moov',
  ONMETA = 'Onmeta',
  ONRAMPMONEY = 'Onramp Money',
  PAYPAL = 'PayPal',
  PAYBIS = 'Paybis',
  PLAID = 'Plaid',
  REVOLUT = 'Revolut',
  ROBINHOOD = 'Robinhood',
  SALTEDGE = 'Saltedge',
  SALTEDGEPARTNERS = 'Salt Edge (Partners)',
  SARDINE = 'Sardine',
  SHIFT4 = 'Shift4',
  SIMPLEX = 'Simplex',
  STRIPE = 'Stripe',
  TOPPER = 'Topper',
  TRANSFI = 'Transfi',
  TRANSAK = 'Transak',
  UNLIMIT = 'Unlimit',
  YELLOWCARD = 'Yellow Card',
  YODLEE = 'Yodlee'
}
