checksumBehavior: update

enableScripts: false

enableTelemetry: false

nmHoistingLimits: workspaces

nmSelfReferences: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.6.4.cjs

packageExtensions:
  "@wdio/utils@*":
    peerDependencies:
      edgedriver: ">=4.0.0"
      geckodriver: ">=4.0.0"
    peerDependenciesMeta:
      edgedriver:
        optional: true
      geckodriver:
        optional: true

  "@appium/support@*":
    peerDependencies:
      sharp: ">=0.33.0"
    peerDependenciesMeta:
      sharp:
        optional: true

  "appium-ios-remotexpc@*":
    peerDependencies:
      appium-ios-tuntap: ">=1.0.0"
    peerDependenciesMeta:
      appium-ios-tuntap:
        optional: true
