export default {
  keypadUpButton: 'keypad_up_button',
  successfullyAdded: 'successfully added',
  backButton: 'header_back',
  inputTextField: 'input_text',
  simpleToastMsg: 'simple_toast_msg',
  jailbrokenWarning: 'jailbroken_warning__text',
  getStartedBtn: 'Get Started',
  retryBtn: 'Retry',
  testnetBanner: 'testnet_banner',
  notNow: 'Not Now',
  turnOnNotifications: 'Turn on Notifications',
  searchBar: 'search_bar',
  bitcoinSVG: 'bitcoin_svg',
  avaSVG: 'ava_logo',
  reloadSVG: 'reload_svg',
  carrotSVG: 'carrot_svg',
  calendarSVG: 'calendarSVG',
  datePicker: 'dateTimePicker',
  okBtn: 'OK',
  next: 'Next',
  dismiss: 'Dismiss',
  dismissAndroid: 'DISMISS',
  grabber: 'grabber',
  cChain: 'Avalanche C-Chain',
  cChain_2: 'Avalanche (C-Chain)',
  pChain: 'Avalanche P-Chain',
  pChain_2: 'Avalanche (P-Chain)',
  pChain_3: 'p_chain',
  xChain: 'Avalanche X-Chain',
  xChain_2: 'Avalanche (X-Chain)',
  xChain_3: 'x_chain',
  xpChain: 'Avalanche X/P-Chain',
  ethereum: 'Ethereum',
  evm: 'Avalanche C-Chain/EVM',
  bitcoinNetwork: 'Bitcoin network',
  bitcoin: 'Bitcoin',
  solana: 'Solana',
  optimism: 'Optimism Mainnet',
  arbitrum: 'Arbitrum One',
  base: 'Base',
  allNetworks: 'All networks',
  balanceHeaderAccountName: 'balance_header_account_name',
  pinInputField: 'pin_input',
  copyPhrase: 'Copy phrase',
  copied: 'Copied',
  save: 'Save',
  dialogInput: 'dialog_input',
  copy: 'Copy',
  selectNetworkBitcoin: 'select_network__Bitcoin',
  selectNetworkCChainEVM: 'select_network__Avalanche C-Chain/EVM',
  selectNetworkXPChain: 'select_network__Avalanche X/P-Chain',
  evmNetwork: 'Avalanche C-Chain/EVM',
  XPNetwork: 'Avalanche X/P-Chain',
  transactionOnboardingNext: 'transaction_onboarding__next',
  tokenAmountInputField: 'token_amount_input_field',
  transactionSuccess: 'Transaction successful',
  nextBtnById: 'next_btn',
  approveBtn: 'approve_button',
  rejectBtn: 'reject_button',
  dropdownScrollView: 'dropdown_scroll_view',
  dropdownItem: 'dropdown_item__',
  settingsBtn: 'account_setting_bar_btn',
  copyBtn: 'copy_btn__',
  myEvmAddress2: '0xF65536cDCbc74960b6a835e5902EB362c458F490',
  myEvmAddress: '0xAa7C5180e46e8c995413B9FbDFEDE46f4B2B9Dc2',
  myXpAddress: 'avax1mv8plj6j92r8gd0syc8n98c4ke5tcvf22kr2w4',
  myBtcAddress: 'bc1q853w4p6q9csh3d0nwe8gjyu43hfkx4m2gn04z6',
  mySolanaAddress: '5MJmmv6SufweTQdmokQn5oiZTigXin7ipKELfc7VPZTy',
  btcbAddress: '0xAa7C5180e46e8c995413B9FbDFEDE46f4B2B9Dc2',
  btcAddress: 'bc1q2f0tczgrukdxjrhhadpft2fehzpcrwrz549u90',
  usdcAddress: '0xb97ef9ef8734c71904d8002f8b6bc66dd9c48a6e',
  ethAddress: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2',
  delete: 'Delete',
  remove: 'Remove',
  cancel: 'Cancel',
  approvePopupTitle: 'Do you approve this transaction?',
  approvePopupSpendTitle: 'Do you approve this spend limit?',
  insufficientBalance: 'Insufficient balance',
  filterDropdown: 'filter_dropdown_btn',
  networkFilterDropdown: 'network_dropdown_btn',
  transactionFail: 'Transaction failed',
  gotIt: 'Got it',
  updateAppModalTitle: 'update_app_title',
  solanaLaunchTitle: 'solana_launch_title',
  account: 'testWallet1',
  accountOneAddress: '0xaa7c5180e46e8c995413b9fbdfede46f4b2b9dc2',
  accountTwoAddress: '0xe7b75ab160cf38f090a099e2e311969acbd25293',
  editedAccount: 'AvaxWallet',
  addAccountButton: 'Add Account',
  addEditAccounts: 'Add/Edit Accounts',
  avaxAddress: 'account_address',
  doneButton: 'Done',
  editAccount: 'Edit',
  saveNewAccountName: 'Save',
  accountOne: 'Account 1',
  secondAccount: 'Account 2',
  fourthaccount: 'Account 4',
  accountDropdownTitle: 'account_dropdown_title',
  accountsDropdown: 'accounts_dropdown',
  editedAccountName: 'Edited Account 2',
  accountBalance: 'account_balance',
  accountTitle: 'account_title',
  usd: 'USD',
  hkd: 'HKD',
  usa: 'United States',
  southKorea: 'South Korea',
  cChainId: '43114',
  ethChainId: '1',
  loadingSpinnerVisible: 'loading_spinner_visible',
  loadingSpinnerHidden: 'loading_spinner_hidden',
  inProgress: 'In progress'
}
