export default {
  // NEW BELOW:
  testnetModeIsOn: 'Testnet mode is on',
  sendButton: 'action_button__Send',
  swapButton: 'action_button__Swap',
  buyButton: 'action_button__Buy',
  bridgeButton: 'action_button__Bridge',
  receiveButton: 'action_button__Receive',
  sort: 'sort_dropdown_btn',
  view: 'view_dropdown_btn',
  portfolioBalanceHeader: 'portfolio__balance_header',
  portfolioAccountName: 'portfolio__balance_header_account_name',
  activityTab: 'Activity',
  addToWatchlist: 'add_svg',
  addAssetsButton: 'Add Assets',
  addAssetsMessage: 'Add assets by clicking the button below.',
  addcustomToken: 'Add custom token',
  arbitrumNetwork: 'Arbitrum One',
  avaxNetwork: 'Avalanche (C-Chain)',
  avaxPNetwork: 'Avalanche (P-Chain)',
  avaxXNetwork: 'Avalanche (X-Chain)',
  avaxFujiToken: 'Avalanche (FUJI)',
  assetsTab: 'Assets',
  btcTokenItem: 'BTC',
  btcNetwork: 'Bitcoin',
  collectiblesTab: 'Collectibles',
  defiTab: 'DeFi',
  ethNetwork: 'Ethereum',
  ethSepoliaNetwork: 'Ethereum Sepolia',
  favoritesHeader: 'Favorites',
  manageNetworks: 'Manage Networks',
  manageTokens: 'Manage',
  networksHeader: 'Networks',
  networksDropdown: 'network_dropdown_btn',
  noAssetsHeader: 'No assets',
  polygonNetwork: 'Polygon',
  viewAll: 'View All',
  sendPendingToast: 'send_token_context__send_pending_toast',
  sendSuccessToast: 'send_token_context__send_successful_toast',
  activeNetwork: 'active_network__',
  inactiveNetwork: 'inactive_network__',
  networkDropdownCheckMark: 'network_dropdown_check_mark__',
  tokensTab: 'Tokens',
  benqi: 'BENQI',
  activeNetworkBalance: 'active_network_balance',
  tokensTabListView: 'tokens_tab_list_view',
  portfolioTokenList: 'portfolio_token_list',
  portfolioTokenItem: 'portfolio_token_item__',
  defiGridTitle: 'defi_grid_title',
  defiListTitle: 'defi_list_title',
  collectibleListTitle: 'nft_list_title',
  defiGridItem: 'defi_grid_item',
  defiListItem: 'defi_list_item',
  defiGridBrowserBtn: 'defi_grid_browser_btn',
  defiListBrowserBtn: 'defi_list_browser_btn',
  defiGridPrice: 'defi_grid_price',
  defiListPrice: 'defi_list_price',
  defiDetailTitle: 'defi_detail_title',
  defiDetailPrice: 'defi_detail_price',
  defiEmptyScreenTitle: 'No positions yet',
  defiEmptyScreenDescription:
    'Discover a wide variety of apps, blockchains, wallets and explorers, built on the Avalanche ecosystem',
  defiEmptyScreenExploreBtn: 'Explore DeFi',
  aaveDefiUrl: 'https://app.aave.com/',
  defiDetailBrowserBtn: 'defi_detail_browser_btn',
  hideBtn: 'action_button__Hide',
  resetFilterBtn: 'Reset filter',
  noCollectiblesTitle: 'No collectibles found',
  noCollectiblesDescription:
    'Try changing the filter settings or reset the filter to see all assets.',
  collectiblesHandler: 'collectibles_handler',
  collectibleHero: 'collectible_hero',
  nftCreatedByTitle: 'list_item__Created by',
  nftStandardTitle: 'right_value__Standard',
  nftChainTitle: 'right_value__Chain',
  refreshBtn: 'refresh_btn',
  setAsMyAvatarBtn: 'set_as_my_avatar_btn',
  nftListItem: 'nft_list_item__',
  managedNft: 'The Free Mint',
  unreachable: 'unreachable',
  untitledNft: 'Untitled',
  untitledDisplayed: 'Untitled_displayed'
}
