export default {
  deleteContactBtn: 'delete_contact_btn',
  addAccountBtn: 'add_account_btn',
  removeAllAccounts: 'Remove all accounts',
  myWallets: 'My wallets',
  account: 'Account 1',
  account2: 'Account 2',
  account3: 'Account 3',
  eyeIcon: 'eye_icon',
  settingsScrollView: 'settings_scroll_view',
  settingsFooter: 'settings_footer',
  iUnderstandBtn: 'I understand, continue',
  analyticsOn: 'analytics_enabled',
  analyticsOff: 'analytics_disabled',
  deleteWalletBtn: 'Delete wallet',
  securityAndPrivacy: 'Security & privacy',
  theme: 'Theme',
  networks: 'Networks',
  themeTitle: 'Customize the',
  system: 'System',
  light: 'Light',
  dark: 'Dark',
  settingsBtn: 'account_setting_bar_btn',
  unselectedAppearance: 'unselected_appearance',
  selectCurrencyTitle: 'Select a currency',
  addWalletBtn: 'add_wallet_btn',
  createNewAccountBtn: 'create_new_account_btn',
  importRecoveryPhraseBtn: 'import_recovery_phrase_btn',
  importPrivateKeyBtn: 'import_private_key_btn',
  accountList: 'account_carousel_list',
  accountDetailIconIdPrefix: 'account_detail_icon__',
  accountCarouselItemIdPrefix: 'account_carousel_item__',
  changePin: 'Change PIN',
  enterYourCurrentPinTitle: `current PIN`,
  enterYourNewPinTitle: 'new PIN',
  confirmYourNewPinTitle: 'Confirm your',
  toggleBiometricsOn: 'toggle_biometrics_on',
  toggleBiometricsOff: 'toggle_biometrics_off',
  unlockWithFaceId: 'Unlock with Face ID',
  showRecoveryPhrase: 'Show recovery phrase',
  showRecoveryPhraseTitle: 'Show recovery',
  privateKey: 'private_key',
  copyKey: 'Copy key',
  imported: 'Imported',
  primary: 'Primary',
  privateKeyDescription: 'private_key_description',
  privateKeyWarning:
    'Anyone with this private key can access the account(s) associated with it',
  showRecoveryPhraseDescription:
    'This phrase is your access key to your wallet. Carefully write it down and store it in a safe location.',
  showRecoveryPhraseWarning: 'Losing this phrase will result in lost funds',
  notificationsPreferences: 'Notification preferences',
  notificationsPreferencesTitle: 'Notification',
  testnetSwitchOn: 'testnet_enabled',
  testnetSwitchOff: 'testnet_disabled',
  testnetModeToast: 'testnet_toast',
  testnetModeOffToast: 'Testnet mode is now off',
  testnetModeOnToast: 'Testnet mode is now on',
  fujiFunds: 'Fuji funds',
  totalNetWorth: 'Total net worth',
  mainnetAvatar: 'mainnet_avatar',
  testnetAvatar: 'testnet_avatar',
  addressCopied: ' address copied',
  renameAccount: 'Rename account',
  removeAccount: 'remove_account',
  removeAccountDisabled: 'remove_account_disabled',
  showPrivateKey: 'Show private key',
  rename: 'Rename',
  addAccountToThisWallet: 'Add account to this wallet',
  removeWallet: 'Remove wallet',
  newAccountName: 'NewName Account 1',
  manageAccountsBtn: 'manage_accounts',
  emptyContacts: 'No saved addresses',
  emptyContactsText: 'Save addresses for quick access in future transactions',
  addAddressButton: 'btn__Add an address',
  connectedSites: 'Connected sites',
  disconnectAll: 'Disconnect all',
  manageAccountsTitle: 'Manage accounts',
  importWalletBtn: 'import_wallet',
  addNetworkBtn: 'add_network_btn',
  chainID: 'chainId',
  arbCustomNetworkName: 'Arbitrum One',
  arbCustomNativeTokenSymbol: 'ETH',
  celoRpcUrl: 'https://forno.celo.org',
  celoNetworkName: 'Celo Mainnet',
  celoWrongNetworkName: 'Kelo Mainnet',
  celoChainID: '42220',
  celoNativeTokenSymbol: 'CELO',
  celoNativeTokenName: 'Celo',
  celoExplorerUrl: 'https://explorer.celo.org',
  networkRpcUrl: 'advanced_title__Network RPC URL',
  chainId: 'advanced_title__Chain ID',
  tokenSymbol: 'advanced_title__Token symbol',
  tokenName: 'advanced_title__Token name',
  explorerUrl: 'advanced_title__Explorer URL',
  iWroteItDownButton: 'I wrote it down',
  contacts: 'Contacts',
  currencyId: 'list_item__Currency',
  currency: 'Currency',
  nameContactBtn: 'name_btn',
  typeInOrPasteAddress: 'Type in or paste address',
  contactPreviewAddress: 'contact_preview_address',
  hkd: 'HKD',
  beamL1: 'Beam L1',
  customAvatar: 'custom_avatar',
  nameThisNetworkBtn: 'Name this network',
  saveNetworkBtn: 'save_network_btn'
}
