export default {
  sendButton: 'action_button__Send',
  swapButton: 'action_button__Swap',
  buyButton: 'action_button__Buy',
  bridgeButton: 'action_button__Bridge',
  receiveButton: 'action_button__Receive',
  accountTwo: 'Account 2',
  accountOneAddress: '0xAa7C5180e46e8c995413B9FbDFEDE46f4B2B9Dc2',
  accountTwoAddress: '0xE7B75AB160cf38F090A099e2e311969aCBD25293',
  addressBook: 'address_book',
  amountField: 'universal_token_selector__amount_field',
  avaxToken: 'AVAX',
  ethToken: 'ETH',
  solToken: 'SOL',
  jupToken: 'JUP',
  coqInu: 'COQ',
  wrappedEthToken: 'WETH',
  btcToken: 'BTC',
  sendingAmount: '0.0001',
  myAccounts: 'My Accounts',
  sendTitle: 'Send',
  amountToSend: 'token_amount_input_field',
  sendSelectTokenListBtn: 'send_select_token_list_btn',
  usdcToken: 'USDC',
  wethToken: 'WETH',
  addressField: 'end_token__send_field',
  searchBarOnSelectToken: 'search_bar__select_token',
  searchBar: 'search_bar',
  selectTokenTitle: 'Select a token',
  sendTo: 'Send To',
  max: 'Max',
  optimism: 'Optimism Mainnet',
  arbitrum: 'Arbitrum One',
  base: 'Base',
  allNetworks: 'All networks',
  balanceHeaderAccountName: 'balance_header_account_name',
  pinInputField: 'pin_input',
  copyPhrase: 'Copy phrase',
  copied: 'Copied',
  save: 'Save',
  dialogInput: 'dialog_input',
  copy: 'Copy',
  selectNetworkBitcoin: 'select_network__Bitcoin',
  selectNetworkCChainEVM: 'select_network__Avalanche C-Chain/EVM',
  selectNetworkXPChain: 'select_network__Avalanche X/P-Chain',
  evmNetwork: 'Avalanche C-Chain/EVM',
  XPNetwork: 'Avalanche X/P-Chain',
  transactionOnboardingNext: 'transaction_onboarding__next',
  transactionSuccess: 'Transaction successful',
  nextBtn: 'next_btn',
  approveBtn: 'approve_button',
  rejectBtn: 'reject_button',
  dropdownScrollView: 'dropdown_scroll_view',
  dropdownItem: 'dropdown_item__',
  settingsBtn: 'account_setting_bar_btn',
  copyBtn: 'copy_btn__',
  myEvmAddress2: '0xF65536cDCbc74960b6a835e5902EB362c458F490',
  myEvmAddress: '0xAa7C5180e46e8c995413B9FbDFEDE46f4B2B9Dc2',
  myXpAddress: 'avax18vaw45gtmc8d3k8ntqdh9ya2fpt5v67syvf6pg',
  myBtcAddress: 'bc1qx0wc08l9kft3zql6p4q62erw00xpe7qntu92eu',
  mySolanaAddress: 'GekYiiiREoGcSayESnkPaX9bnPvYaahEDXdDbUdccpwy',
  btcbAddress: '0xAa7C5180e46e8c995413B9FbDFEDE46f4B2B9Dc2',
  btcAddress: 'bc1q2f0tczgrukdxjrhhadpft2fehzpcrwrz549u90',
  usdcAddress: '0xb97ef9ef8734c71904d8002f8b6bc66dd9c48a6e',
  ethAddress: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2',
  delete: 'Delete',
  cancel: 'Cancel',
  approvePopupTitle: 'Do you approve this transaction?',
  approvePopupSpendTitle: 'Do you approve this spend limit?',
  insufficientBalance: 'Insufficient balance',
  filterDropdown: 'filter_dropdown_btn',
  networkFilterDropdown: 'network_dropdown_btn',
  transactionFail: 'Transaction failed',
  gotIt: 'Got it',
  updateAppModalTitle: 'update_app_title',
  solanaLaunchTitle: 'solana_launch_title',
  youPay: 'select_token_title__You pay',
  youReceive: 'select_token_title__You receive',
  trackBuyBtn: 'trending_token_buy_btn__',
  errorMsg: 'error_msg',
  cChain: 'Avalanche (C-Chain)',
  solana: 'Solana',
  swapText: 'Swap',
  swapVerticalIcon: 'swap_vertical_icon',
  trendingDetailSwapBtn: 'token_detail_swap_btn'
}
