export default {
  activeTab: 'Active',
  historyTab: 'History',
  amountStakedText: 'Amount Staked',
  earnedRewardsText: 'Earned Rewards',
  endDateText: 'End Date',
  doneButtonText: 'Done',
  firstStakeText: 'Stake #01',
  stakedAmountText: 'Staked Amount',
  earnSvg: 'earnSVG',
  noActiveStakesTitle: 'No Active Stakes',
  noActiveStakesDescription: 'Press "Stake" above to begin staking.',
  estimatedRewardsText: 'Estimated Rewards',
  estimatedRewardsTooltip: 'info_svg',
  availableAvaxText: 'Available',
  avaLogo: 'ava_logo',
  avaxText: 'AVAX',
  availableBalance: 'available_balance',
  balanceTooltip: 'info_svg',
  balanceTooltipText: 'Final staking amount may be slightly lower due to fees',
  stakedAvaxText: 'Staked',
  confirmationTitle: 'Confirm Staking',
  claimableAvaxText: 'Claimable',
  claimableBalance: 'claimable_balance',
  stakeTitle: 'Stake',
  notEnoughAvaxTitle: '25 AVAX required',
  notEnoughAvaxDescription: 'You need at least 25 AVAX to stake.',
  nextButton: 'next_btn',
  swapAvaxButton: 'Swap AVAX',
  recieveAvaxButton: 'Receive AVAX',
  buyAvaxButton: 'Buy AVAX',
  switchNetworkTitle: 'Switch Network to Stake',
  switchNetworkDescription:
    'Staking is only available on the Avalanche Network. Please switch networks to continue.',
  switchNetworkButton: 'btnPrimary',
  switchNetworkButtonText: 'Switch to Avalanche Network',
  stakeButtonPrimary: 'stake_btn',
  stakeButtonSecondary: 'stake_btn_secondary',
  stakeButtonText: 'Stake',
  stakeNow: 'confirm_btn',
  cancel: 'cancel_btn',
  cancelModal: 'warning_modal_button',
  stakingAmountTitle: 'Staking Amount',
  stakingAmountDescription: 'How many AVAX would you like to stake?',
  inputAmount: 'token_base_unit_input',
  notNowButton: 'warning_modal_button',
  newStakeTimeRemaining: '1 day remaining',
  usdText: 'USD',
  topBalanceItem: 'balance_item',
  tenPercentText: '10%',
  twentyFivePercentText: '25%',
  fiftyPercentText: '50%',
  maxText: 'Max',
  stakeClaimButton: 'stake_claim_btn',
  stakeCardTitle: 'stake_card_title',
  stakeDetailsTitle: 'stake_details_title',
  completedStatusChip: 'Completed_status_chip',
  activeStatusChip: 'Ongoing_status_chip',
  timeRemaining: 'Time Remaining',
  transactionIdText: 'Transaction ID',
  estimatedRewardsId: 'estimated_rewards',
  timeRemainingId: 'time_remaining',
  stakedAmountId: 'staked_amount',
  endDateId: 'end_date',
  earnedRewardsId: 'earned_rewards',
  stakingSuccessful: 'Staking successful!',
  customRadio: 'Custom',
  customInput: 'custom_network_fee_input',
  customSaveBtn: 'custom_network_fee_save_btn',
  customBaseFee: 'custom_base_fee',
  slowBaseFee: 'slow_base_fee',
  fastBaseFee: 'fast_base_fee',
  instantBaseFee: 'instant_base_fee',
  durationScreenTitle: 'Duration'
}
