export default {
  activeTab: 'Active',
  historyTab: 'History',
  amountStakedText: 'Amount Staked',
  earnedRewardsText: 'Earned Rewards',
  endDateText: 'End Date',
  doneButtonText: 'Done',
  firstStakeText: 'Stake #01',
  stakedAmountText: 'Staked Amount',
  earnSvg: 'earnSVG',
  noActiveStakesTitle: 'No Active Stakes',
  noActiveStakesDescription: 'Press "Stake" above to begin staking.',
  estimatedRewardsText: 'Estimated Rewards',
  estimatedRewardsTooltip: 'info_svg',
  availableAvaxText: 'Available',
  avaLogo: 'ava_logo',
  avaxText: 'AVAX',
  availableBalance: 'available_balance',
  balanceTooltip: 'info_svg',
  balanceTooltipText: 'Final staking amount may be slightly lower due to fees',
  stakedAvaxText: 'Staked',
  confirmationTitle: 'Confirm Staking',
  claimableAvaxText: 'Claimable',
  stakeTitle: 'Stake',
  notEnoughAvaxTitle: '25 AVAX required',
  notEnoughAvaxDescription: 'You need at least 25 AVAX to stake.',
  nextButton: 'next_btn',
  swapAvaxButton: 'Swap AVAX',
  recieveAvaxButton: 'Receive AVAX',
  buyAvaxButton: 'Buy AVAX',
  switchNetworkTitle: 'Switch Network to Stake',
  switchNetworkDescription:
    'Staking is only available on the Avalanche Network. Please switch networks to continue.',
  switchNetworkButton: 'btnPrimary',
  switchNetworkButtonText: 'Switch to Avalanche Network',
  stakeButtonPrimary: 'stake_btn',
  stakeButtonSecondary: 'stake_btn_secondary',
  stakeButtonText: 'Stake',
  stakeNow: 'confirm_btn',
  stakingAmountTitle: 'Staking Amount',
  stakingAmountDescription: 'How many AVAX would you like to stake?',
  inputAmount: 'token_base_unit_input',
  notNowButton: 'warning_modal_button',
  newStakeTimeRemaining: '1 day remaining',
  usdText: 'USD',
  topBalanceItem: 'balance_item',
  tenPercentText: '10%',
  twentyFivePercentText: '25%',
  fiftyPercentText: '50%',
  maxText: 'Max'
}
