export enum ViewOnceKey {
  CHART_INTERACTION,
  BROWSER_INTERACTION,
  ANALYTICS_CONSENT,
  X_CHAIN_FAVORITE,
  DEFAULT_WATCHLIST_FAVORITES,
  NOTIFICATIONS_PROMPT,
  HALLIDAY_BANNER,
  STAKE_ONBOARDING,
  BRIDGE_ONBOARDING,
  SWAP_ONBOARDING,
  SEND_ONBOARDING,
  MIGRATE_TOKEN_FAVORITE_IDS,
  AUTO_ENABLE_L2_CHAINS
}

export type ViewOnceObjectType = {
  [key in ViewOnceKey]: boolean
}

export type ViewOnceState = {
  data: ViewOnceObjectType
}
