#source 'https://github.com/CocoaPods/Specs.git'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

#install! 'cocoapods', :deterministic_uuids => false

platform :ios, '11.0'

target 'AvaxWallet' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  target 'AvaxWalletTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!({ 'Flipper' => '0.93.0', 'Flipper-Folly' => '2.6.9', 'Flipper-RSocket' => '1.4.3'})

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

end

post_install do |installer|
 flipper_post_install(installer)
 react_native_post_install(installer)

 installer.pods_project.targets.each do |target|
   target.build_configurations.each do |config|
     config.build_settings['SWIFT_VERSION'] = 4.2
     config.build_settings['ENABLE_BITCODE'] = 'NO'
     config.build_settings['ARCHS'] = '$(ARCHS_STANDARD_64_BIT)'
     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
     
     if target.name.include? 'Flipper' or target.name.include? 'Folly'
       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
     end
   end
 end
end
