export default {
  advanced: 'Advanced',
  addressBook: 'Address Book',
  AddAddressButton: 'Add Address',
  backbutton: 'header_back',
  burgerbutton: 'menu_svg',
  changePin: 'Change PIN',
  contactAvaxAddress: '0x19E5ECB3F15197E7A72996259C2245919C9725dD',
  contactBtcAddress: 'tb1qwausd68f03kyxcr7qvqwunehut5npl7eeccvna',
  contactName: 'Avax account 2',
  copyPhraseButton: 'Copy Phrase',
  carrotSvg: 'carrot_svg',
  currency: 'Currency',
  delete: 'Delete',
  deleteContact: 'Delete Contact',
  edit: 'Edit',
  emptyContacts: 'No Addresses Saved',
  emptyContactsText: 'Tap the button below to add an address.',
  enterYourPinHeader: 'Enter your pin',
  euroCurrency: 'Euro (EUR)',
  euroSign: 'EUR',
  firstMnemonicWord: 'rebel',
  lastMnemonicWord: 'embark',
  nameText: 'Name',
  newContactName: 'Avax account 2 New',
  recoveeryPhraseHeader: 'Recovery Phrase',
  saveButton: 'Save',
  setNewPinHeader: 'Set new pin',
  securityAndPrivacy: 'Security & Privacy',
  showRecoveryPhrase: 'Show recovery phrase',
  switchButton: 'switch',
  inputTextField: 'input_text',
  iWroteItDownButton: 'I wrote it down',
  usdCurrency: 'United States Dollar (USD)',
  usdSign: 'USD'
}
