export default {
  gridItem: 'baseGridItem',
  sendButton: 'btnSecondary',
  addressInput: 'input_text',
  addressBook: 'address_book',
  cancelButton: 'btnSecondary',
  myAccounts: 'My Accounts',
  nextButton: 'btnPrimary',
  nftTokenId: 'NftTokenID',
  nftTokenName: 'NftTokenName',
  nftTokenTitle: 'NftTokenTitle',
  sendNowButton: 'btnPrimary',
  sendSuccessfulToastMsg: 'Send Successful',
  descriptionTitle: 'Description',
  createdByTitle: 'Created by',
  floorPriceTitle: 'Floor price',
  propertiesTitle: 'Properties',
  fromText: 'From',
  toText: 'To',
  networkFeeText: 'Network Fee',
  sendTitle: 'Send',
  collectibleText: 'Collectible',
  nftlogo: 'avatar__logo_avatar'
}
