export default {
  addNetwork: 'add_svg',
  bitcoinTestnet: 'Bitcoin Testnet',
  chainID: 'Chain ID',
  customRpcUrl: 'https://arb1.arbitrum.io/rpc',
  customNetworkName: 'Arbitrum Ones',
  newCustomNetworkName: 'Arbitrum One',
  customChainID: '42161',
  customNativeTokenSymbol: 'ETH',
  customExplorerUrl: 'https://arbiscan.io/',
  customTab: 'Custom',
  dropdown: 'ellipsis_svg',
  deleteNetwork: 'Delete',
  editNetwork: 'Edit',
  ethereumGoerlyNetwork: 'Ethereum Goerli',
  ethTokenOnCustomNetwork: 'ETH',
  explorerUrl: 'Explorer URL',
  favoriteNetwork: 'star_svg',
  favoritesTab: 'Favorites',
  headerBack: 'header_back',
  inputTextField: 'input_text',
  nativeTokenSymbol: 'Native Token Symbol',
  networkName: 'Network Name',
  networkRpcUrl: 'Network RPC URL',
  networksTab: 'Networks',
  networkInfo: 'info_svg',
  saveButton: 'Save'
}
