export default {
  addAddressButton: 'Add Address',
  emptyContacts: 'No Addresses Saved',
  emptyContactsText: 'Tap the button below to add an address.',
  deleteContact: 'delete_contact',
  edit: 'Edit',
  contactName: 'Avax account 2',
  nameText: 'Name',
  contactAvaxAddress: '0x19E5ECB3F15197E7A72996259C2245919C9725dD',
  contactBtcAddress: 'tb1qwausd68f03kyxcr7qvqwunehut5npl7eeccvna',
  saveButton: 'save_btn',
  newContactName: 'Avax account 2 New',
  delete: 'Delete',
  newContact: 'New Contact',
  nameField: 'contact_input__name',
  addressField: 'contact_input__address',
  btcAddressField: 'contact_input__btc_address',
  pChainAddressField: 'contact_input__p_chain_address',
  back: 'header_back'
}
