export default {
  account: 'testWallet1',
  accountOneAddress: '0xaa7c5180e46e8c995413b9fbdfede46f4b2b9dc2',
  accountTwoAddress: '0xe7b75ab160cf38f090a099e2e311969acbd25293',
  editedAccount: 'AvaxWallet',
  addAccountButton: 'Add Account',
  addEditAccounts: 'Add/Edit Accounts',
  avaxAddress: 'account_address',
  doneButton: 'Done',
  editAccount: 'Edit',
  saveNewAccountName: 'Save',
  accountOne: 'Account 1',
  secondAccount: 'Account 2',
  fourthaccount: 'Account 4',
  accountDropdownTitle: 'account_dropdown_title',
  accountsDropdown: 'accounts_dropdown',
  editedAccountName: 'Edited Account 2',
  accountBalance: 'account_balance',
  accountTitle: 'account_title'
}
