export default {
  account: 'testWallet1',
  accountOneAddress: '0x1eaecc18b1ce33a2dffa01bc3a5e421344999027',
  accountTwoAddress: '0xf65536cdcbc74960b6a835e5902eb362c458f490',
  editedAccount: 'AvaxWallet',
  addAccountButton: 'Add Account',
  addEditAccounts: 'Add/Edit Accounts',
  avaxAddress: 'account_address',
  doneButton: 'Done',
  editAccount: 'Edit',
  saveNewAccountName: 'Save',
  accountOne: 'Account 1',
  secondAccount: 'Account 2',
  fourthaccount: 'Account 4',
  accountDropdownTitle: 'account_dropdown_title',
  accountsDropdown: 'accounts_dropdown',
  editedAccountName: 'Edited Account 2',
  accountBalance: 'account_balance',
  accountTitle: 'account_title'
}
