export default {
  transaction: 'activity_list__Contract Call',
  activityDetail: 'activity_detail__amount',
  activityListItem: 'activityListItem',
  bridgeActivityListItem: 'bridgeActivityListItem',
  activityListItemAmount: 'acitivty_item_amount',
  avaxOutgoingTransactionDetail: '-0.0001 AVAX',
  avaxIncomingTransactionDetail: '+0.0001 AVAX',
  ethOutgoingTransactionDetail: '-0.0001 ETH',
  ethIncomingTransactionDetail: '+0.0001 ETH',
  currentFilter: 'activity_list__current_filter',
  filterOptionBridge: 'activity_list__filter_Bridge',
  filterOptionContractCall: 'activity_list__filter_Contract Call',
  filterOptionIncoming: 'activity_list__filter_Incoming',
  filterOptionOutgoing: 'activity_list__filter_Outgoing',
  bridgeTransaction: 'bridge_transaction__item',
  bridgeSVG: 'bridge_svg',
  networkIcon: 'network_icon',
  arrowUpSVG: 'primary_netowork_icon__Send',
  linkIcon: 'link_svg',
  usdcOutgoingTransactionDetail: '-0.0001 USDC',
  usdcIncomingTransactionDetail: '+0.0001 USDC',
  wethOutgoingTransactionDetail: '-0.0001 WETH.e',
  wethIncomingTransactionDetail: '+0.0001 WETH.e',
  noRecentActivity: 'No recent activity',
  allFilter: 'All',
  sentFilter: 'Sent',
  receivedFilter: 'Received',
  swapFilter: 'Swap',
  bridgeFilter: 'Bridge'
}
