export default {
  avalancheNetwork: 'Avalanche C-Chain',
  avaxEthBridgeTransaction: '0.055 WETH.e',
  avaxBtcBridgeTransaction: '0.0024 BTC.b',
  amountToLowBtcAvaxMessage: 'Amount too low -- minimum is 0.002400000',
  btcToken: 'Bitcoin',
  bitcoinNetwork: 'Bitcoin',
  btcAvaxBridgeTransaction: '0.0024 BTC',
  bridgeSuccessfulToastMsg: 'Bridge Successful',
  closebutton: 'Close',
  ethereumNetwork: 'Ethereum',
  ethereumTestNetwork: 'Ethereum Goerli',
  ethBridgeTransaction: '0.055 WETH',
  hide: 'Hide',
  headerBack: 'header_back',
  selectTokenDropdown: 'Select Token',
  wrappedEther: 'Wrapped Ether',
  inputTextField: 'input_text',
  tokenValueAvaxBtc: '0.0024',
  tokenValueEthAvax: '0.055',
  tokenValueBtcAvax: '0.0024',
  tokenValueAvaxEth: '0.055',
  from: 'From',
  transferButton: 'Transfer',
  sendingAmmount: 'Sending amount',
  networkFee: 'Network Fee',
  confirmations: 'Confirmations',
  to: 'To',
  completedStatusEth: '96/96',
  completedStatusAvax: '1/1',
  completedStatusBtcAvaxMainnet: '6/6',
  completedStatusBtcAvaxTestnet: '4/4'
}
