export default {
  avalancheNetwork: 'Avalanche (C-Chain)',
  avaxEthBridgeTransaction: '0.055 WETH.e',
  avaxBtcBridgeTransaction: '0.0024 BTC.b',
  amountToLowBtcAvaxMessage: 'Amount too low -- minimum is 0.002400000',
  btcToken: 'Bitcoin',
  bitcoinNetwork: 'Bitcoin',
  btcAvaxBridgeTransaction: '0.0024 BTC',
  bridgeSuccessfulToastMsg: 'Bridge Successful',
  closebutton: 'Close',
  ethereumNetwork: 'Ethereum',
  ethereumTestNetwork: 'Ethereum Sepolia',
  ethBridgeTransaction: '0.055 WETH',
  hide: 'Hide',
  selectTokenDropdown: 'Select Token',
  wrappedEther: 'Wrapped Ether',
  inputTextField: 'input_text',
  tokenValueAvaxBtc: '0.0024',
  tokenValueEthAvax: '0.055',
  tokenValueBtcAvax: '0.0024',
  tokenValueAvaxEth: '0.055',
  from: 'From',
  transferButton: 'Transfer',
  sendingAmmount: 'Sending amount',
  networkFee: 'Network Fee',
  confirmations: 'Confirmations',
  to: 'To',
  completedStatusEth: '96/96',
  completedStatusAvax: '1/1',
  completedStatusBtcAvaxMainnet: '6/6',
  completedStatusBtcAvaxTestnet: '4/4',
  bridgeTitle: 'Bridge',
  bridgeBtn: 'bridge_btn',
  receive: 'Receive',
  bridgeToggleBtn: 'bridge_toggle_btn',
  selectedToken: 'selected_token',
  toNetwork: 'to_blockchain',
  fromNetwork: 'From',
  error: 'bridge_error',
  hollidayBannerWebView: 'halliday-bridge-webview',
  hollidayBannerTitle: 'Bridge using Halliday',
  hollidayBannerContent:
    'Buy and bridge USD and other currencies directly to L1s using Halliday.'
}
