export default {
  gridItem: 'baseGridItem',
  sendButton: 'send_btn',
  saveBtn: 'Save',
  addressInput: 'input_text',
  addressBook: 'address_book',
  cancelButton: 'btnSecondary',
  customFeeButton: 'Custom',
  customFeeInput: 'input_text',
  myAccounts: 'My Accounts',
  nextButton: 'next_btn',
  nftTokenId: 'NftTokenID',
  nftTokenName: 'NftTokenName',
  nftTokenTitle: 'NftTokenTitle',
  descriptionTitle: 'Description',
  createdByTitle: 'Created by',
  floorPriceTitle: 'Floor price',
  transactionDetails: 'Transaction Details',
  account: 'Account',
  type: 'Type',
  nftlogo: 'avatar__logo_avatar',
  warningAddressRequired: 'Address required',
  warningInsufficientFee: 'Insufficient balance for fee.',
  paradiseTycoonFurnituresNFT: 'token_id_4491',
  nftItem: 'nft_item',
  listSvg: 'list_svg',
  nftListView: 'nft_list_view',
  testingNft: 'mint' // Eunji added a lot of NFTs named `mint` on mnemonic wallet for testing purpose.
}
