export default {
  gridItem: 'nft_grid_item',
  sendButton: 'send_btn',
  saveBtn: 'Save',
  addressInput: 'input_text',
  addressBook: 'address_book',
  cancelButton: 'btnSecondary',
  customFeeButton: 'Custom',
  customFeeInput: 'input_text',
  myAccounts: 'My Accounts',
  nextButton: 'next_btn',
  nftTokenId: 'NftTokenID',
  nftTokenName: 'NftTokenName',
  nftTokenTitle: 'NftTokenTitle',
  descriptionTitle: 'Description',
  createdByTitle: 'Created by',
  floorPriceTitle: 'Floor price',
  transactionDetails: 'Transaction Details',
  account: 'Account',
  type: 'Type',
  nftlogo: 'avatar__logo_avatar',
  warningAddressRequired: 'Address required',
  warningInsufficientFee: 'Insufficient balance for fee',
  nftItem: 'nft_item',
  listSvg: 'list_svg',
  nftListView: 'nft_list_view',
  invalidNFT: '#7452 ',
  manageNft: 'Manage',
  testingNft: 'mint',
  handler: 'collectibles_handler'
}
