export default {
  gridItem: 'baseGridItem',
  sendButton: 'btnSecondary',
  saveBtn: 'Save',
  addressInput: 'input_text',
  addressBook: 'address_book',
  cancelButton: 'btnSecondary',
  customFeeButton: 'Custom',
  customFeeInput: 'input_text',
  myAccounts: 'My Accounts',
  nextButton: 'btnPrimary',
  nftTokenId: 'NftTokenID',
  nftTokenName: 'NftTokenName',
  nftTokenTitle: 'NftTokenTitle',
  sendNowButton: 'btnPrimary',
  sendSuccessfulToastMsg: 'Send Successful',
  descriptionTitle: 'Description',
  createdByTitle: 'Created by',
  floorPriceTitle: 'Floor price',
  propertiesTitle: 'Properties',
  fromText: 'From',
  toText: 'To',
  networkFeeText: 'Network Fee',
  sendTitle: 'Send',
  collectibleText: 'Collectible',
  nftlogo: 'avatar__logo_avatar',
  warningAddressRequired: 'Address required',
  warningInsufficientFee: 'Insufficient balance for fee.'
}
