export default {
  backButton: 'header_back',
  inputTextField: 'input_text',
  simpleToastMsg: 'simple_toast_msg',
  jailbrokenWarning: 'jailbroken_warning__text',
  getStartedBtn: 'Get Started',
  retryBtn: 'Retry',
  testnetBanner: 'testnet_banner',
  notNow: 'Not Now',
  turnOnNotifications: 'Turn on Notifications',
  searchBar: 'search_bar__search',
  bitcoinSVG: 'bitcoin_svg',
  avaSVG: 'ava_logo',
  reloadSVG: 'reload_svg',
  carrotSVG: 'carrot_svg',
  calendarSVG: 'calendarSVG',
  datePicker: 'dateTimePicker',
  okBtn: 'OK',
  next: 'Next',
  dismiss: 'Dismiss'
}
