export default {
  backButton: 'header_back',
  inputTextField: 'input_text',
  simpleToastMsg: 'simple_toast_msg',
  jailbrokenWarning: 'jailbroken_warning__text',
  getStartedBtn: 'Get Started',
  retryBtn: 'Retry',
  testnetBanner: 'testnet_banner',
  notNow: 'Not Now',
  turnOnNotifications: 'Turn on Notifications',
  searchBar: 'search_bar__search',
  bitcoinSVG: 'bitcoin_svg',
  avaSVG: 'ava_logo',
  reloadSVG: 'reload_svg',
  carrotSVG: 'carrot_svg',
  calendarSVG: 'calendarSVG',
  datePicker: 'dateTimePicker',
  okBtn: 'OK',
  next: 'Next',
  dismiss: 'Dismiss',
  grabber: 'grabber',
  viewDropdownBtn: 'view_dropdown_btn',
  cChain: 'Avalanche C-Chain',
  cChain_2: 'Avalanche (C-Chain)',
  pChain: 'Avalanche P-Chain',
  pChain_2: 'Avalanche (P-Chain)',
  xChain: 'Avalanche X-Chain',
  xChain_2: 'Avalanche (X-Chain)',
  ethereum: 'Ethereum',
  bitcoinNetwork: 'Bitcoin network',
  bitcoin: 'Bitcoin',
  allNetworks: 'All networks',
  balanceHeaderAccountName: 'balance_header_account_name'
}
