export default {
  backButton: 'header_back',
  inputTextField: 'input_text',
  simpleToastMsg: 'simple_toast_msg',
  jailbrokenWarning: 'jailbroken_warning__text',
  getStartedBtn: 'Get Started',
  retryBtn: 'Retry',
  testnetBanner: 'testnet_banner',
  notNow: 'Not Now',
  turnOnNotifications: 'Turn on Notifications',
  searchBar: 'search_bar',
  bitcoinSVG: 'bitcoin_svg',
  avaSVG: 'ava_logo',
  reloadSVG: 'reload_svg',
  carrotSVG: 'carrot_svg',
  calendarSVG: 'calendarSVG',
  datePicker: 'dateTimePicker',
  okBtn: 'OK',
  next: 'Next',
  dismiss: 'Dismiss',
  grabber: 'grabber',
  cChain: 'Avalanche C-Chain',
  cChain_2: 'Avalanche (C-Chain)',
  pChain: 'Avalanche P-Chain',
  pChain_2: 'Avalanche (P-Chain)',
  xChain: 'Avalanche X-Chain',
  xChain_2: 'Avalanche (X-Chain)',
  xpChain: 'Avalanche X/P-Chain',
  ethereum: 'Ethereum',
  evm: 'Avalanche C-Chain/EVM',
  bitcoinNetwork: 'Bitcoin network',
  bitcoin: 'Bitcoin',
  solana: 'Solana',
  allNetworks: 'All networks',
  balanceHeaderAccountName: 'balance_header_account_name',
  pinInputField: 'pin_input',
  copyPhrase: 'Copy phrase',
  copied: 'Copied',
  save: 'Save',
  dialogInput: 'dialog_input',
  copy: 'Copy',
  selectNetworkBitcoin: 'select_network__Bitcoin',
  selectNetworkCChainEVM: 'select_network__Avalanche C-Chain/EVM',
  selectNetworkXPChain: 'select_network__Avalanche X/P-Chain',
  evmNetwork: 'Avalanche C-Chain/EVM',
  XPNetwork: 'Avalanche X/P-Chain',
  transactionOnboardingNext: 'transaction_onboarding__next',
  tokenAmountInputField: 'token_amount_input_field',
  transactionSuccess: 'Transaction successful',
  nextBtn: 'next_btn',
  approveBtn: 'approve_button',
  rejectBtn: 'reject_button',
  dropdownScrollView: 'dropdown_scroll_view',
  dropdownItem: 'dropdown_item__',
  settingsBtn: 'account_setting_bar_btn',
  copyBtn: 'copy_btn__',
  myEvmAddress: '0x6bD4f76e2c0453bFC6F7177542808E22A4Ee323F',
  myEvmAddress2: '0x1EAECC18B1cE33a2dfFA01bc3A5E421344999027',
  myXpAddress: 'avax1ahvdv7f3sqlt6vqkvx3lhvruck6035f0k0hjky',
  myBtcAddress: 'bc1qpj62svx5wpldpnhs0qf40e5rfnvwnj92gkrjv9',
  mySolanaAddress: 'HbQz5cmmtKwttc763uLZ6QJQSUGSkfoA2zFDpuavmsTs',
  btcbAddress: '0x1EAECC18B1cE33a2dfFA01bc3A5E421344999027',
  btcAddress: 'bc1q2f0tczgrukdxjrhhadpft2fehzpcrwrz549u90',
  usdcAddress: '0xb97ef9ef8734c71904d8002f8b6bc66dd9c48a6e',
  ethAddress: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2',
  delete: 'Delete',
  cancel: 'Cancel',
  approvePopupTitle: 'Do you approve this transaction?',
  approvePopupSpendTitle: 'Do you approve this spend limit?',
  insufficientBalance: 'Insufficient balance',
  filterDropdown: 'filter_dropdown_btn',
  networkFilterDropdown: 'network_dropdown_btn',
  transactionFail: 'Transaction failed'
}
