export default {
  addNetwork: 'add_svg',
  bitcoinTestnet: 'Bitcoin Testnet',
  chainID: 'Chain ID',
  arbCustomRpcUrl: 'https://arb1.arbitrum.io/rpc',
  arbCustomNetworkName: 'Arbitrum One',
  arbWrongCustomNetworkName: 'Arbitrum Ones',
  arbCustomChainID: '42161',
  arbCustomNativeTokenSymbol: 'ETH',
  arbCustomExplorerUrl: 'https://arbiscan.io/',
  polygonCustomNetworkName: 'Polygon Mainnet',
  polygonCustomRpcUrl: 'https://polygon-rpc.com/',
  polygonCustomChainID: '137',
  polygonCustomNativeTokenSymbol: 'MATIC',
  polygonCustomExplorerUrl: 'https://polygonscan.com/',
  customTab: 'Custom',
  dropdown: 'ellipsis_svg',
  deleteNetwork: 'Delete',
  editNetwork: 'Edit',
  ethereumSepoliaNetwork: 'Ethereum Sepolia',
  ethTokenOnCustomNetwork: 'ETH',
  explorerUrl: 'Explorer URL',
  favoriteNetwork: 'star_svg',
  favoritesTab: 'Favorites',
  headerBack: 'header_back',
  inputTextField: 'input_text',
  nativeTokenSymbol: 'Native Token Symbol',
  networkName: 'Network Name',
  networkRpcUrl: 'Network RPC URL',
  networksTab: 'Networks',
  networkInfo: 'info_svg',
  saveButton: 'Save',
  searchBar: 'network_manager__search_input'
}
