export default {
  addNetwork: 'add_svg',
  chainID: 'chainId',
  arbCustomNetworkName: 'Arbitrum One',
  arbCustomNativeTokenSymbol: 'ETH',
  celoRpcUrl: 'https://forno.celo.org',
  celoNetworkName: 'Celo Mainnet',
  celoWrongNetworkName: 'Kelo Mainnet',
  celoChainID: '42220',
  celoNativeTokenSymbol: 'CELO',
  celoNativeTokenName: 'Celo',
  celoExplorerUrl: 'https://explorer.celo.org',
  polygonCustomNetworkName: 'Polygon',
  polygonCustomRpcUrl: 'https://polygon-rpc.com/',
  polygonCustomChainID: '137',
  polygonCustomNativeTokenSymbol: 'MATIC',
  polygonCustomExplorerUrl: 'https://polygonscan.com/',
  customTab: 'Custom',
  dropdown: 'ellipsis_svg',
  deleteNetwork: 'Delete',
  editNetwork: 'Edit',
  ethereumSepoliaNetwork: 'Ethereum Sepolia',
  bitcoinTestnetNetwork: 'Bitcoin Testnet',
  ethTokenOnCustomNetwork: 'Ether',
  explorerUrl: 'explorerUrl',
  favoriteNetwork: 'star_svg',
  favoritesTab: 'Favorites',
  inputTextField: 'input_text',
  nativeTokenSymbol: 'nativeTokenSymbol',
  networkName: 'networkName',
  networkRpcUrl: 'networkRpcUrl',
  networksTab: 'Networks',
  saveButton: 'save_btn',
  starSvg: 'star_svg',
  networkNotAvailableToast: 'network_not_available_toast',
  bitcoin: 'Bitcoin',
  networkRPCUrlText: 'Network RPC URL',
  nativeTokenName: 'nativeTokenName',
  logoURL: 'logoUri',
  chainIdText: 'Chain ID',
  explorerUrlText: 'Explorer URL',
  noCustomNetworks: 'No custom networks',
  networkTokenSymbol: 'Network Token Symbol',
  networkTokenNameText: 'Network Token Name',
  avaxRpcUrl: 'https://api.avax.network/ext/bc/C/rpc',
  avaxChainID: '43114',
  avaxSymbol: 'AVAX',
  avaxTokenName: 'Avalanche',
  avaxExplorerUrl: 'https://subnets.avax.network/c-chain',
  ethRpcUrl: 'https://proxy-api.avax.network/proxy/infura/mainnet',
  ethChainID: '1',
  ethNetworkSymbol: 'ETH',
  ethNetworkTokenName: 'Ethereum',
  ethExplorerUrl: 'https://etherscan.io',
  connect: 'Connect'
}
