export default {
  addNetwork: 'add_svg',
  editNetworkTitle: 'Edit Network',
  chainID: 'chainId',
  arbCustomNetworkName: 'Arbitrum One',
  arbCustomNativeTokenSymbol: 'ETH',
  celoRpcUrl: 'https://forno.celo.org',
  celoNetworkName: 'Celo Mainnet',
  celoWrongNetworkName: 'Kelo Mainnet',
  celoChainID: '42220',
  celoNativeTokenSymbol: 'CELO',
  celoExplorerUrl: 'https://explorer.celo.org',
  polygonCustomNetworkName: 'Polygon',
  polygonCustomRpcUrl: 'https://polygon-rpc.com/',
  polygonCustomChainID: '137',
  polygonCustomNativeTokenSymbol: 'MATIC',
  polygonCustomExplorerUrl: 'https://polygonscan.com/',
  customTab: 'Custom',
  dropdown: 'ellipsis_svg',
  deleteNetwork: 'Delete',
  editNetwork: 'Edit',
  ethereumSepoliaNetwork: 'Ethereum Sepolia',
  bitcoinTestnetNetwork: 'Bitcoin Testnet',
  ethTokenOnCustomNetwork: 'Ether',
  explorerUrl: 'explorerUrl',
  favoriteNetwork: 'star_svg',
  favoritesTab: 'Favorites',
  headerBack: 'header_back',
  inputTextField: 'input_text',
  nativeTokenSymbol: 'nativeTokenSymbol',
  networkName: 'networkName',
  networkRpcUrl: 'networkRpcUrl',
  networksTab: 'Networks',
  networkInfo: 'info_svg',
  saveButton: 'save_btn',
  searchBar: 'network_manager__search_input',
  starSvg: 'star_svg',
  networkNotAvailableToast: 'network_not_available_toast',
  bitcoin: 'Bitcoin',
  networkRPCUrl: 'Network RPC URL',
  nativeTokenName: 'nativeTokenName',
  logoURL: 'logoUri',
  chainIdText: 'Chain ID',
  explorerUrlText: 'Explorer URL',
  noCustomNetworks: 'No custom networks'
}
