export default {
  manuallyCreateNewWallet: 'manually_create_new_wallet_button',
  accessExistingWallet: 'accessExistingWallet',
  continueWithGoogle: 'continueWithGoogle',
  continueWithApple: 'continueWithApple',
  accessExistingWalletBtn: 'Access existing wallet',
  enterPinFirstScreenTitle: 'Secure your wallet\nwith a PIN',
  enterPinFirstScreenDescription:
    'For extra security, avoid choosing a PIN that contains repeating digits in a sequential order',
  enterPinSecondScreenTitle: 'Confirm your\nPIN code',
  walletName: 'testWallet1',
  selectAvatarTitle: 'Select your\npersonal avatar',
  selectAvatarDescription:
    "Add a display avatar for your wallet. You can change it at any time in the app's settings",
  selectedAvatar: 'selected_avatar',
  chooseWalletTitle: 'How would you like to access your existing wallet?',
  addWalletUsingKeystone: 'Add using Keystone',
  typeRecoverPhase: 'Type in a recovery phrase',
  createNewWalletBtn: 'Create a new wallet',
  noThanksBtn: 'No thanks',
  unlockBtn: 'Unlock',
  analysticsTitle: 'Unlock airdrops',
  analysticsContentId: 'anlaysticsContent',
  agreeAndContinue: 'Agree and continue',
  termsAndConditions: 'Terms and conditions',
  termsAndConditionsDescription: 'terms_conditions_description',
  continueButton: 'Continue',
  recoveryPhraseInput: `text_area__recovery_phrase`,
  recoveryPhraseHeader: 'recovery_phrase__header',
  cancelButton: 'Cancel',
  testWalletLink: 'hd_wallet_login__test_wallet',
  alreadyHaveAWalletBtn: 'Already Have a Wallet?',
  signInWithRecoveryPhrase: 'Sign in with Recovery Phrase',
  forgotPin: 'Forgot PIN?',
  manuallyCreateNewWalletBtn: 'manually_create_new_wallet_button',
  enterYourRecoveryPhraseTitle: 'Enter your\nrecovery phrase',
  enterYourRecoveryPhraseDescription:
    'This phrase should contain 12, 18, or 24 words. Use a space between each word.',
  import: `Import`,
  nameWalletInput: 'text_input',
  nameWalletTitle: 'Add a name for your wallet',
  letsgo: 'lets_go_btn',
  confirmationTitle: `That's it!\nEnjoy your wallet`,
  confirmationDescription:
    'You can now start buying, swapping, sending, receiving crypto and collectibles',
  newRecoveryPhraseTitle: "Here is your wallet's recovery phrase",
  newRecoveryPhraseDescription:
    'This phrase is your access key to your wallet. Carefully write it down and store it in a safe location',
  newRecoveryPhraseWarning: 'Losing this phrase will result in lost funds',
  securityWarningTitle: 'Security warning',
  securityWarningContent:
    'For your security, you should not screenshot your recovery phrase. It is best to write it down and store it in a secure location.',
  verifyYourRecoveryPhraseTitle: 'Verify your recovery phrase',
  verifyYourRecoveryPhraseDescription: `Select the words below to verify your\nrecover phrase`
}
