export default {
  toastMessage: 'Transaction Successful',
  linkSvg: 'link_svg',
  approveBtn: 'approve_button',
  rejectBtn: 'reject_button',
  rejectTextBtn: 'Reject',
  type: 'Type',
  account: 'Account:',
  approveTransactionTitle: 'Approve Transaction',
  approveExportTitle: 'Approve Export',
  approveImportTitle: 'Approve Import',
  addDelegator: 'Add Delegator',
  maximumNetworkFee: 'Maximum Network Fee',
  balanceChange: 'Balance Change',
  successfulToastMsg: 'Transaction Successful',
  network: 'Network:',
  transactionDetails: 'Transaction Details',
  feeAmount: 'Fee Amount',
  signMessage: 'Sign Message',
  messageTitle: 'Message:',
  scamTransaction: 'Scam Transaction',
  scamTransactionContent: 'This transaction is malicious, do not proceed.',
  rejectTransaction: 'Reject Transaction',
  proceedAnyway: 'Proceed Anyway',
  switchToSepoliaNetworkTitle: 'Switch to Sepolia Network?',
  switchToFujiNetworkTitle: 'Switch to Avalanche (C-Chain) Network?',
  createContact: 'Create Contact?',
  messageDetail: 'message_detail',
  tokenGasFee: 'token_gas_fee',
  tokenAmount: 'token_amount',
  popUpModalScrollView: 'approve_popup_scroll_view',
  slowBaseFee: 'slow_base_fee',
  customBaseFee: 'custom_base_fee',
  successToast: 'success_toast',
  connectBtn: 'Connect',
  noSitesFound: 'No sites found',
  disconnectAll: 'Disconnect all'
}
