export default {
  toastMessage: 'Transaction Successful',
  linkSvg: 'link_svg',
  approveBtn: 'approve_button',
  rejectBtn: 'reject_button',
  type: 'Type',
  account: 'Account:',
  approveTransactionTitle: 'Approve Transaction',
  maximumNetworkFee: 'Maximum Network Fee',
  balanceChange: 'Balance Change',
  successfulToastMsg: 'Transaction Successful',
  network: 'Network:',
  transactionDetails: 'Transaction Details',
  feeAmount: 'Fee Amount',
  signMessage: 'Sign Message',
  messageTitle: 'Message:',
  scamTransaction: 'Scam Transaction',
  scamTransactionContent: 'This transaction is malicious, do not proceed.',
  rejectTransaction: 'Reject Transaction',
  proceedAnyway: 'Proceed Anyway',
  switchToSepoliaNetwork: 'Switch to Sepolia Network?',
  switchToFujiNetwork: 'Switch to Avalanche (C-Chain) Network?',
  createContact: 'Create Contact?',
  messageDetail: 'message_detail',
  tokenGasFee: 'token_gas_fee',
  tokenAmount: 'token_amount'
}
