export default {
  activityTab: 'Activity',
  addToWatchlist: 'add_svg',
  addAssetsButton: 'Add Assets',
  addAssetsMessage: 'Add assets by clicking the button below.',
  addcustomToken: 'Add custom token',
  arbitrumNetwork: 'Arbitrum One',
  avaxNetwork: 'Avalanche (C-Chain)',
  avaxFujiToken: 'Avalanche (FUJI)',
  assetsTab: 'Assets',
  btcTokenItem: 'BTC',
  btcNetwork: 'Bitcoin',
  collectiblesTab: 'Collectibles',
  defiTab: 'DeFi',
  ethNetwork: 'Ethereum',
  ethSepoliaNetwork: 'Ethereum Sepolia',
  favoritesHeader: 'Favorites',
  manageNetworks: 'Manage networks',
  manageTokens: 'Manage',
  networksHeader: 'Networks',
  networksDropdownBTC: 'network_dropdown__Bitcoin',
  networksDropdownAVAX: 'network_dropdown__Avalanche (C-Chain)',
  networksDropdownETH: 'network_dropdown__Ethereum',
  networksDropdownManage: 'network_dropdown__Manage Networks',
  networksDropdown: 'network_dropdown_main',
  noAssetsHeader: 'No assets',
  polygonNetwork: 'Polygon Mainnet',
  viewAll: 'View All'
}
