export default {
  activityTab: 'Activity',
  addToWatchlist: 'add_svg',
  addAssetsButton: 'Add Assets',
  addAssetsMessage: 'Add assets by clicking the button below.',
  addcustomToken: 'Add custom token',
  arbitrumNetwork: 'Arbitrum One',
  avaxNetwork: 'Avalanche (C-Chain)',
  avaxPNetwork: 'Avalanche (P-Chain)',
  avaxXNetwork: 'Avalanche (X-Chain)',
  avaxFujiToken: 'Avalanche (FUJI)',
  assetsTab: 'Assets',
  btcTokenItem: 'BTC',
  btcNetwork: 'Bitcoin',
  collectiblesTab: 'Collectibles',
  defiTab: 'DeFi',
  ethNetwork: 'Ethereum',
  ethSepoliaNetwork: 'Ethereum Sepolia',
  favoritesHeader: 'Favorites',
  manageNetworks: 'Manage Networks',
  manageTokens: 'Manage',
  networksHeader: 'Networks',
  networksDropdownItem: 'network_dropdown__',
  networksDropdownBTC: 'network_dropdown__Bitcoin',
  networksDropdownBTCTestNet: 'network_dropdown__Bitcoin Testnet',
  networksDropdownAVAX: 'network_dropdown__Avalanche (C-Chain)',
  networksDropdownPChain: 'network_dropdown__Avalanche (P-Chain)',
  networksDropdownXChain: 'network_dropdown__Avalanche (X-Chain)',
  networksDropdownETH: 'network_dropdown__Ethereum',
  networksDropdownManage: 'network_dropdown__Manage Networks',
  networksDropdown: 'network_dropdown_main',
  noAssetsHeader: 'No assets',
  polygonNetwork: 'Polygon',
  viewAll: 'View All',
  sendPendingToast: 'send_token_context__send_pending_toast',
  sendSuccessToast: 'send_token_context__send_successful_toast',
  activeNetwork: 'active_network__',
  inactiveNetwork: 'inactive_network__',
  networkDropdownCheckMark: 'network_dropdown_check_mark__',
  tokensTab: 'Tokens',
  benqi: 'BENQI',
  activeNetworkBalance: 'active_network_balance',
  tokensTabListView: 'tokens_tab_list_view',
  portfolioTokenList: 'portfolio_token_list'
}
