export default {
  accountTwo: 'Account 2',
  accountOneAddress: '0xAa7C5180e46e8c995413B9FbDFEDE46f4B2B9Dc2',
  accountTwoAddress: '0xE7B75AB160cf38F090A099e2e311969aCBD25293',
  addressBook: 'address_book',
  amountField: 'universal_token_selector__amount_field',
  avaxToken: 'AVAX',
  ethToken: 'ETH',
  solToken: 'SOL',
  jupToken: 'JUP',
  coqInu: 'COQ',
  wrappedEthToken: 'WETH',
  btcToken: 'BTC',
  sendingAmount: '0.0001',
  myAccounts: 'My Accounts',
  nextBtn: 'next_btn',
  sendTitle: 'Send',
  amountToSend: 'universal_token_selector__amount_field',
  sendSelectTokenListBtn: 'send_select_token_list_btn',
  usdcToken: 'USDC',
  wethToken: 'WETH.e',
  approveBtn: 'approve_button',
  rejectBtn: 'Reject',
  addressField: 'end_token__send_field',
  searchBarOnSelectToken: 'search_bar__select_token',
  selectTokenTitle: 'Select a token',
  sendTo: 'Send To',
  max: 'Max'
}
