export default {
  accountTwo: 'Account 2',
  addressBook: 'address_book',
  amountField: 'universal_token_selector__amount_field',
  avaxToken: 'AVAX',
  ethToken: 'ETH',
  wrappedEthToken: 'WETH',
  btcToken: 'BTC',
  sendingAmount: '0.00001',
  myAccounts: 'My Accounts',
  nextBtn: 'next_btn',
  sendTitle: 'Send',
  amountToSend: 'universal_token_selector__amount_field',
  sendSelectTokenListBtn: 'send_select_token_list_btn',
  usdcToken: 'USDC',
  wethToken: 'WETH.e',
  approveBtn: 'approve_button',
  rejectBtn: 'Reject',
  addressField: 'end_token__send_field',
  searchBarOnSelectToken: 'search_bar__select_token',
  selectTokenTitle: 'Select Token',
  sendTo: 'Send To',
  max: 'Max'
}
