export default {
  addressBook: 'address_book',
  amountField: 'universal_token_selector__amount_field',
  avaxToken: 'AVAX',
  ethToken: 'ETH',
  wrappedEthToken: 'WETH',
  btcToken: 'BTC',
  sendingAmount: '0.00001',
  myAccounts: 'My Accounts',
  nextBtn: 'next_btn',
  sendTitle: 'Send',
  amountToSend: 'universal_token_selector__amount_field',
  tokenDropdown: 'send_token__token_dropdown',
  usdcToken: 'USDC',
  wethToken: 'WETH.e',
  approveBtn: 'approve_button',
  rejectBtn: 'Reject',
  addressField: 'end_token__send_field',
  searchBarOnSelectToken: 'search_bar__select_token',
  selectTokenTitle: 'Select Token',
  sendTo: 'Send To',
  max: 'Max',
  gaslessError:
    'Core was unable to fund the gas. You will need to pay the gas fee to continue with this transaction.',
  gaslessSwitch: 'gasless_switch'
}
