export default {
  // NEW BELOW:
  eyeIcon: 'eye_icon',
  settingsFooter: 'settings_footer',
  settingsScrollView: 'settings_scroll_view',
  iUnderstandBtn: 'I understand, continue',
  analyticsOn: 'analytics_enabled',
  analyticsOff: 'analytics_disabled',
  deleteWalletBtn: 'Delete wallet',
  securityAndPrivacy: 'Security & privacy',
  securityAndPrivacyTitle: 'Security\n& privacy',
  appearance: 'Theme',
  appearanceTitle: 'Customize the\napp theme',
  system: 'System',
  light: 'Light',
  dark: 'Dark',
  settingsBtn: 'account_setting_bar_btn',
  unselectedAppearance: 'unselected_appearance',
  selectCurrencyTitle: 'Select a currency',
  addAccountBtn: 'add_account_btn',
  accountList: 'account_list',
  accountNameIdPrefix: 'account_name__account #',
  accountDetailIconIdPrefix: 'account_detail_icon__account #',
  changePin: 'Change PIN',
  enterYourCurrentPinTitle: 'Enter your current PIN',
  enterYourNewPinTitle: 'Enter your\nnew PIN',
  confirmYourNewPinTitle: 'Confirm your\nnew PIN',
  toggleBiometricsOn: 'toggle_biometrics_on',
  toggleBiometricsOff: 'toggle_biometrics_off',
  unlockWithFaceId: 'Unlock with Face ID',
  showRecoveryPhrase: 'Show recovery phrase',
  showRecoveryPhraseTitle: 'Show recovery\nphrase',
  showRecoveryPhraseDescription:
    'This phrase is your access key to your wallet. Carefully write it down and store it in a safe location.',
  showRecoveryPhraseWarning: 'Losing this phrase will result in lost funds',
  notificationsPreferences: 'Notification preferences',
  notificationsPreferencesTitle: 'Notification\npreferences',
  testnetSwitchOn: 'testnet_enabled',
  testnetSwitchOff: 'testnet_disabled',
  testnetModeToast: 'testnet_toast',
  testnetModeOffToast: 'Testnet mode is now off',
  fujiFunds: 'Fuji funds',
  totalNetWorth: 'Total net worth',
  mainnetAvatar: 'mainnet_avatar',
  testnetAvatar: 'testnet_avatar',
  cChainAddressCopyBtn: 'copy_c_chain_address',
  pChainAddressCopyBtn: 'copy_p_chain_address',
  xChainAddressCopyBtn: 'copy_x_chain_address',
  ethAddressCopyBtn: 'copy_ethereum_address',
  btcAddressCopyBtn: 'copy_bitcoin_address',
  cChainAddressCopyToast: 'C-Chain address copied',
  pChainAddressCopyToast: 'P-Chain address copied',
  xChainAddressCopyToast: 'X-Chain address copied',
  ethAddressCopyToast: 'Ethereum address copied',
  btcAddressCopyToast: 'Bitcoin address copied',
  renameAccount: 'Rename account',
  newAccountName: 'New account name 1',
  manageAccountsBtn: 'manage_accounts',
  firstAccountName: 'Wallet 1',
  // OLD BELOLW:
  connectedSites: 'Connected Sites',
  participateInCoreAnalytics: 'Participate in Core analytics',
  firstMnemonicWord: 'rebel',
  lastMnemonicWord: 'embark',
  iWroteItDownButton: 'I wrote it down',
  advanced: 'Advanced',
  addressBook: 'Address Book',
  AddAddressButton: 'Add Address',
  burgerbutton: 'menu_svg',
  currency: 'Currency',
  saveButton: 'Save'
}
