export default {
  // NEW BELOW:
  walletName: 'testWallet1',
  account: 'Account 1',
  account2: 'Account 2',
  eyeIcon: 'eye_icon',
  settingsFooter: 'settings_footer',
  settingsScrollView: 'settings_scroll_view',
  iUnderstandBtn: 'I understand, continue',
  analyticsOn: 'analytics_enabled',
  analyticsOff: 'analytics_disabled',
  deleteWalletBtn: 'Delete wallet',
  securityAndPrivacy: 'Security & privacy',
  securityAndPrivacyTitle: 'Security\n& privacy',
  appearance: 'Theme',
  networks: 'Networks',
  appearanceTitle: 'Customize the\napp appearance',
  system: 'System',
  light: 'Light',
  dark: 'Dark',
  settingsBtn: 'account_setting_bar_btn',
  unselectedAppearance: 'unselected_appearance',
  selectCurrencyTitle: 'Select a currency',
  addWalletBtn: 'add_wallet_btn',
  createNewAccountBtn: 'create_new_account_btn',
  accountList: 'account_carousel_list',
  accountDetailIconIdPrefix: 'account_detail_icon__',
  accountCarouselItemIdPrefix: 'account_carousel_item__',
  changePin: 'Change PIN',
  enterYourCurrentPinTitle: 'Enter your current PIN',
  enterYourNewPinTitle: 'Enter your\nnew PIN',
  confirmYourNewPinTitle: 'Confirm your\nnew PIN',
  toggleBiometricsOn: 'toggle_biometrics_on',
  toggleBiometricsOff: 'toggle_biometrics_off',
  unlockWithFaceId: 'Unlock with Face ID',
  showRecoveryPhrase: 'Show recovery phrase',
  showRecoveryPhraseTitle: 'Show recovery\nphrase',
  showRecoveryPhraseDescription:
    'This phrase is your access key to your wallet. Carefully write it down and store it in a safe location.',
  showRecoveryPhraseWarning: 'Losing this phrase will result in lost funds',
  notificationsPreferences: 'Notification preferences',
  notificationsPreferencesTitle: 'Notification\npreferences',
  testnetSwitchOn: 'testnet_enabled',
  testnetSwitchOff: 'testnet_disabled',
  testnetModeToast: 'testnet_toast',
  testnetModeOffToast: 'Testnet mode is now off',
  fujiFunds: 'Fuji funds',
  totalNetWorth: 'Total net worth',
  mainnetAvatar: 'mainnet_avatar',
  testnetAvatar: 'testnet_avatar',
  addressCopied: ' address copied',
  renameAccount: 'Rename account',
  newAccountName: 'NewName Account 1',
  manageAccountsBtn: 'manage_accounts',
  firstAccountName: 'Wallet 1',
  emptyContacts: 'No saved addresses',
  emptyContactsText: 'Save addresses for quick access in future transactions',
  addAddressButton: 'Add an address',
  connectedSites: 'Connected sites',
  disconnectAll: 'Disconnect all',
  manageAccountsTitle: 'Manage accounts',
  addNetworkBtn: 'add_network_btn',
  // OLD BELOW:
  addNetwork: 'add_svg',
  chainID: 'chainId',
  arbCustomNetworkName: 'Arbitrum One',
  arbCustomNativeTokenSymbol: 'ETH',
  celoRpcUrl: 'https://forno.celo.org',
  celoNetworkName: 'Celo Mainnet',
  celoWrongNetworkName: 'Kelo Mainnet',
  celoChainID: '42220',
  celoNativeTokenSymbol: 'CELO',
  celoNativeTokenName: 'Celo',
  celoExplorerUrl: 'https://explorer.celo.org',
  polygonCustomNetworkName: 'Polygon',
  polygonCustomRpcUrl: 'https://polygon-rpc.com/',
  polygonCustomChainID: '137',
  polygonCustomNativeTokenSymbol: 'MATIC',
  polygonCustomExplorerUrl: 'https://polygonscan.com/',
  customTab: 'Custom',
  dropdown: 'ellipsis_svg',
  deleteNetwork: 'Delete',
  editNetwork: 'Edit',
  ethereumSepoliaNetwork: 'Ethereum Sepolia',
  bitcoinTestnetNetwork: 'Bitcoin Testnet',
  ethTokenOnCustomNetwork: 'Ether',
  explorerUrl: 'explorerUrl',
  favoriteNetwork: 'star_svg',
  favoritesTab: 'Favorites',
  inputTextField: 'input_text',
  nativeTokenSymbol: 'nativeTokenSymbol',
  networkName: 'networkName',
  networkRpcUrl: 'networkRpcUrl',
  networksTab: 'Networks',
  saveButton: 'save_btn',
  starSvg: 'star_svg',
  networkNotAvailableToast: 'network_not_available_toast',
  bitcoin: 'Bitcoin',
  networkRPCUrlText: 'Network RPC URL',
  nativeTokenName: 'nativeTokenName',
  logoURL: 'logoUri',
  chainIdText: 'Chain ID',
  explorerUrlText: 'Explorer URL',
  noCustomNetworks: 'No custom networks',
  networkTokenSymbol: 'Network Token Symbol',
  networkTokenNameText: 'Network Token Name',
  avaxRpcUrl: 'https://api.avax.network/ext/bc/C/rpc',
  avaxChainID: '43114',
  avaxSymbol: 'AVAX',
  avaxTokenName: 'Avalanche',
  avaxExplorerUrl: 'https://subnets.avax.network/c-chain',
  ethRpcUrl: 'https://proxy-api.avax.network/proxy/infura/mainnet',
  ethChainID: '1',
  ethNetworkSymbol: 'ETH',
  ethNetworkTokenName: 'Ethereum',
  ethExplorerUrl: 'https://etherscan.io',
  connect: 'Connect',
  participateInCoreAnalytics: 'Participate in Core analytics',
  firstMnemonicWord: 'rebel',
  lastMnemonicWord: 'embark',
  iWroteItDownButton: 'I wrote it down',
  advanced: 'Advanced',
  contacts: 'Contacts',
  AddAddressButton: 'Add Address',
  burgerbutton: 'menu_svg',
  currency: 'Currency',
  nameContactBtn: 'name_btn',
  typeInOrPasteAddress: 'Type in or paste address',
  contactAddressInput: 'contact_address_input',
  contactPreviewAddress: 'contact_preview_address'
}
