export default {
  // NEW BELOW:
  walletName: 'testWallet1',
  account: 'Account 1',
  account2: 'Account 2',
  eyeIcon: 'eye_icon',
  settingsFooter: 'settings_footer',
  settingsScrollView: 'settings_scroll_view',
  iUnderstandBtn: 'I understand, continue',
  analyticsOn: 'analytics_enabled',
  analyticsOff: 'analytics_disabled',
  deleteWalletBtn: 'Delete wallet',
  securityAndPrivacy: 'Security & privacy',
  securityAndPrivacyTitle: 'Security\n& privacy',
  appearance: 'Theme',
  networks: 'Networks',
  appearanceTitle: 'Customize the\napp theme',
  system: 'System',
  light: 'Light',
  dark: 'Dark',
  settingsBtn: 'account_setting_bar_btn',
  unselectedAppearance: 'unselected_appearance',
  selectCurrencyTitle: 'Select a currency',
  addWalletBtn: 'add_wallet_btn',
  createNewAccountBtn: 'create_new_account_btn',
  accountList: 'account_carousel_list',
  accountDetailIconIdPrefix: 'account_detail_icon__',
  accountCarouselItemIdPrefix: 'account_carousel_item__',
  changePin: 'Change PIN',
  enterYourCurrentPinTitle: 'Enter your current PIN',
  enterYourNewPinTitle: 'Enter your\nnew PIN',
  confirmYourNewPinTitle: 'Confirm your\nnew PIN',
  toggleBiometricsOn: 'toggle_biometrics_on',
  toggleBiometricsOff: 'toggle_biometrics_off',
  unlockWithFaceId: 'Unlock with Face ID',
  showRecoveryPhrase: 'Show recovery phrase',
  showRecoveryPhraseTitle: 'Show recovery\nphrase',
  showRecoveryPhraseDescription:
    'This phrase is your access key to your wallet. Carefully write it down and store it in a safe location.',
  showRecoveryPhraseWarning: 'Losing this phrase will result in lost funds',
  notificationsPreferences: 'Notification preferences',
  notificationsPreferencesTitle: 'Notification\npreferences',
  testnetSwitchOn: 'testnet_enabled',
  testnetSwitchOff: 'testnet_disabled',
  testnetModeToast: 'testnet_toast',
  testnetModeOffToast: 'Testnet mode is now off',
  fujiFunds: 'Fuji funds',
  totalNetWorth: 'Total net worth',
  mainnetAvatar: 'mainnet_avatar',
  testnetAvatar: 'testnet_avatar',
  addressCopied: ' address copied',
  renameAccount: 'Rename account',
  newAccountName: 'NewName Account 1',
  manageAccountsBtn: 'manage_accounts',
  firstAccountName: 'Wallet 1',
  emptyContacts: 'No saved addresses',
  emptyContactsText: 'Save addresses for quick access in future transactions',
  addAddressButton: 'Add an address',
  connectedSites: 'Connected sites',
  disconnectAll: 'Disconnect all',
  // OLD BELOW:
  participateInCoreAnalytics: 'Participate in Core analytics',
  firstMnemonicWord: 'rebel',
  lastMnemonicWord: 'embark',
  iWroteItDownButton: 'I wrote it down',
  advanced: 'Advanced',
  contacts: 'Contacts',
  AddAddressButton: 'Add Address',
  burgerbutton: 'menu_svg',
  currency: 'Currency',
  saveButton: 'Save',
  nameContactBtn: 'name_contact_btn',
  typeInOrPasteAddress: 'Type in or paste address',
  contactAddressInput: 'contact_address_input',
  contactPreviewAddress: 'contact_preview_address'
}
