export default {
  availableSupply: 'token_detail__available_supply',
  favorite: 'star_svg',
  marketCap: 'token_detail__market_cap',
  oneWeekTab: '1W',
  oneMonthTab: '1M',
  oneYearTab: '1Y',
  price: 'token_detail__price',
  rank: 'token_detail__rank',
  twitterHandle: 'token_detail__twitter_handle',
  twitter: 'token_detail__twitter',
  websiteUrl: 'token_detail__website_url',
  totalSupply: 'token_detail__total_supply',
  twentyFourHourTab: '24H',
  threeMonthTab: '3M',
  volume: 'token_detail__24h_volume',
  sendBtn: 'send_token_action_btn',
  receiveBtn: 'receive_token_action_btn',
  bridgeBtn: 'bridge_token_action_btn',
  swapBtn: 'swap_token_action_btn',
  holdAndDrag: 'Hold and Drag',
  holdAndDragContent: 'Hold and drag over chart for precise price and date',
  gotItBtn: 'Got it',
  lineGraph: 'line_graph',
  footerBuyBtn: 'token_detail_footer_buy_btn',
  footerSwapBtn: 'token_detail_footer_swap_btn',
  footerStakeBtn: 'token_detail_footer_stake_btn'
}
