export default {
  allTab: 'All',
  existingWalletbtn: 'Existing Wallet',
  favoritesTab: 'Favorites',
  trendingTab: 'Trending',
  newWalletIcon: 'create_new_wallet_plus_svg',
  newWalletBtn: 'New Wallet',
  recoverWalletBtn: `no_wallet_tab_navigator__recover_wallet_btn`,
  walletSVG: 'wallet_svg',
  enterWalletBtn: 'btnPrimary',
  alreadyHaveAWalletBtn: 'Already Have a Wallet?',
  recoveryPhrase: 'Recovery Phrase',
  searchBar: 'search_bar',
  topTrendingTokenName: 'trending_token_name__1',
  topTrendingTokenSymbol: 'trending_token_symbol__1',
  topTrendingTokenValue: 'trending_token_value__1',
  topTrendingTokenBuyBtn: 'trending_token_buy_btn__1',
  topTrendingTokenViewBtn: 'trending_token_view_btn__1',
  topTrendingTokenCrown: 'trending_token_crown__1',
  trackBuyBtn: 'track_buy_btn',
  trackViewBtn: 'track_view_btn',
  starFilled: 'star_filled',
  starOutline: 'star_outline',
  tokenDetailSwapBtn: 'token_detail_swap_btn'
}
