// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "translation": {
    "Account": "Account",
    "Receive": "Receive",
    "Send": "Send",
    "Settings": "Settings"
  }
}
