name: Trigger Bitrise build-apps-internal pipeline

on:
  issue_comment:
    types: [created]

jobs:
  trigger-bitrise-pipeline:
    # Only run for PR comments starting with /bitrise build
    if: |
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/bitrise build')
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Bitrise internal pipeline
        env:
          BITRISE_APP_SLUG: ${{ secrets.BITRISE_APP_SLUG }}
          BITRISE_ACCESS_TOKEN: ${{ secrets.BITRISE_ACCESS_TOKEN }}
          HEAD_REF: ${{ github.event.issue.pull_request.head.ref }}
          HEAD_REPO: ${{ github.event.issue.pull_request.head.repo.full_name }}
          COMMIT_SHA: ${{ github.event.issue.pull_request.head.sha }}
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          echo "Triggering Bitrise pipeline: build-apps-internal"
          curl -X POST "https://api.bitrise.io/v0.1/apps/${BITRISE_APP_SLUG}/pipelines" \
            -H "Authorization: ${BITRISE_ACCESS_TOKEN}" \
            -H "Content-Type: application/json" \
            -d '{
              "pipeline_id": "build-apps-internal",
              "build_params": {
                "branch": "'"${HEAD_REF}"'",
                "commit_hash": "'"${COMMIT_SHA}"'",
                "commit_message": "Triggered from GitHub comment: '${COMMENT_BODY}'",
                "pull_request_repository_url": "https://github.com/'"${HEAD_REPO}"'"
              },
              "triggered_by": "GitHub Action PR comment"
            }'
